import fs from "node:fs";import path from "node:path";import{fileURLToPath}from"node:url";import{CANVASES,DEFAULTS,FIXTURES,evaluateVortex,seamProbe,crossingProbe,summarize}from"./evaluator.mjs"
const here=path.dirname(fileURLToPath(import.meta.url)),sceneRoot=path.dirname(here),vectorsPath=path.join(sceneRoot,"TEST_VECTORS.json"),evidencePath=path.join(sceneRoot,"evidence","TEST_VECTOR_READBACK.json"),vectors=JSON.parse(fs.readFileSync(vectorsPath,"utf8")),failures=[],readback=[];const check=(condition,message)=>{if(!condition)failures.push(message)},near=(a,b,e=1e-9)=>Math.abs(a-b)<=e
for(const vector of vectors.vectors){const items=FIXTURES[vector.input.fixture],state=evaluateVortex({items,config:{...DEFAULTS,...(vector.input.config||{})},normalizedTime:vector.input.normalizedTime,canvas:CANVASES[vector.input.canvas],runKind:vector.input.runKind||"loop",reducedMotion:Boolean(vector.input.reducedMotion),spotlightId:vector.input.spotlightId||items[Math.min(3,items.length-1)]?.id,finaleId:vector.input.finaleId||items.at(-1)?.id}),summary=summarize(state);readback.push({id:vector.id,summary});for(const[key,value]of Object.entries(vector.expect))check(JSON.stringify(summary[key])===JSON.stringify(value),`${vector.id}: expected ${key}=${JSON.stringify(value)}, got ${JSON.stringify(summary[key])}`);check(state.cards.every(card=>card.artworkOpacity===1&&card.artworkFilter==="none"&&card.artworkBlend==="normal"),`${vector.id}: source fidelity drift`);check(state.renderNodeCount<=state.maxObservedNodes,`${vector.id}: node budget exceeded`);check(new Set(state.cards.map(card=>card.id)).size===state.cards.length,`${vector.id}: source identity duplicated`)}
const start=evaluateVortex({items:FIXTURES.ordinary8,config:DEFAULTS,normalizedTime:0,canvas:CANVASES["16:9"]}),end=evaluateVortex({items:FIXTURES.ordinary8,config:DEFAULTS,normalizedTime:1,canvas:CANVASES["16:9"]});check(near(start.phase,end.phase),"loop phase seam mismatch");for(const card of start.cards){const other=end.cards.find(candidate=>candidate.id===card.id);check(Boolean(other)&&near(card.x,other.x)&&near(card.y,other.y)&&near(card.depth,other.depth)&&card.visible===other.visible,`loop seam mismatch ${card.id}`)}
const forward=evaluateVortex({items:FIXTURES.ordinary8,config:{...DEFAULTS,direction:"forward"},normalizedTime:.237,canvas:CANVASES["16:9"]}),reverse=evaluateVortex({items:FIXTURES.ordinary8,config:{...DEFAULTS,direction:"reverse"},normalizedTime:.237,canvas:CANVASES["16:9"]});check(near(forward.phase,modInverse(reverse.phase)),"reverse phase not exact inverse");function modInverse(value){return((1-value)%1+1)%1}
const baseline=evaluateVortex({items:FIXTURES.ordinary8,config:DEFAULTS,normalizedTime:.119,canvas:CANVASES["16:9"]});for(const[id,value,predicate]of[["turns",5,(a,b)=>a.cards.some((card,i)=>!near(card.depth,b.cards[i].depth))],["radialSpread",.45,(a,b)=>a.cards.some((card,i)=>!near(card.x,b.cards[i].x))],["depthPitch",.41,(a,b)=>a.cards.some((card,i)=>!near(card.y,b.cards[i].y))],["cardSize",.29,(a,b)=>a.cards.some((card,i)=>!near(card.width,b.cards[i].width))],["direction","reverse",(a,b)=>!near(a.phase,b.phase)]]){const altered=evaluateVortex({items:FIXTURES.ordinary8,config:{...DEFAULTS,[id]:value},normalizedTime:.119,canvas:CANVASES["16:9"]});check(predicate(altered,baseline),`control ${id} inert`);const reset=evaluateVortex({items:FIXTURES.ordinary8,config:DEFAULTS,normalizedTime:.119,canvas:CANVASES["16:9"]});check(JSON.stringify(reset)===JSON.stringify(baseline),`control ${id} reset not exact`)}
const seam=seamProbe();for(const sample of seam.filter(sample=>sample.seamZone)){check(!sample.visible,`seam sample visible at ${sample.time}`);check(sample.outsideWithMargin||sample.depth<-.95,`seam sample lacks geometric cover at ${sample.time}`)}
const crossings=crossingProbe();let orderChanges=0;for(let i=1;i<crossings.length;i+=1)if(JSON.stringify(crossings[i].ordered)!==JSON.stringify(crossings[i-1].ordered))orderChanges+=1;check(orderChanges>4,"front/rear z-order did not change across crossings")
const equalityA=evaluateVortex({items:FIXTURES.mixed21,config:DEFAULTS,normalizedTime:.456789,canvas:CANVASES["4:5"]}),equalityB=evaluateVortex({items:FIXTURES.mixed21,config:DEFAULTS,normalizedTime:.456789,canvas:CANVASES["4:5"]});check(JSON.stringify(equalityA)===JSON.stringify(equalityB),"same-input/time equality failed")
const receipt={sceneId:"spiral-image-vortex",evaluatorVersion:1,vectorCount:vectors.vectors.length,pass:failures.length===0,failures,seamProbe:seam,crossingOrderChanges:orderChanges,loopSeam:{phaseStart:start.phase,phaseEnd:end.phase},readback};fs.writeFileSync(evidencePath,`${JSON.stringify(receipt,null,2)}\n`);if(failures.length){console.error(failures.join("\n"));process.exit(1)}console.log(`vortex verify: PASS (${vectors.vectors.length} vectors)`)
