import assert from "node:assert/strict"
import {sceneMeta,makeFixture,defaultControls,compileTimeline,evaluateScene,sourceVideoTimeSeconds} from "./evaluator.mjs"
const base=defaultControls();const state=(fixture,time,options={})=>{const items=makeFixture(fixture),controls={...base,...(options.controls??{})},timeline=compileTimeline({mode:options.mode??"automatic",itemCount:items.length,controls,direction:options.direction??"forward"});return evaluateScene({items,controls,timeline,timeMs:time*timeline.durationMs,width:options.width??1920,height:options.height??1080,reducedMotion:options.reducedMotion??false,debug:false,selectedIndex:options.selectedIndex??0})}
for(const fixture of ["one","two","recommended","bounded-many","mixed-failed"]){const start=state(fixture,0),end=state(fixture,1);const order=s=>[...s.cards].sort((a,b)=>a.sourceIndex-b.sourceIndex);assert.deepEqual(order(start).map(c=>c.id),order(end).map(c=>c.id));for(let i=0;i<start.cards.length;i+=1){const a=order(start)[i],b=order(end)[i];assert.ok(Math.hypot(a.x-b.x,a.y-b.y)<1e-7);assert.equal(a.visible,b.visible);assert.equal(a.artworkOpacity,1);assert.equal(a.artworkFilter,"none");assert.equal(a.blendMode,"normal")}}
const oneA=state("one",.1),oneB=state("one",.8);assert.ok(Math.hypot(oneA.cards[0].x-oneB.cards[0].x,oneA.cards[0].y-oneB.cards[0].y)<1e-9);assert.equal(oneA.selectedIndex,0)
const twoTimeline=compileTimeline({mode:"automatic",itemCount:2,controls:base});let previous=null;let directionChanges=0;for(let step=0;step<400;step+=1){const s=state("two",step/400);const p=s.trackProgress;if(previous!==null){let delta=p-previous;if(delta<-.9)delta+=2;if(delta>1.1)delta-=2;if(delta< -1e-7)directionChanges+=1}previous=p}assert.equal(directionChanges,0,"two items must scan in one direction, not oscillate")
const portrait=state("recommended",.4,{width:1080,height:1920});assert.equal(portrait.station.vertical,true);const landscape=state("recommended",.4,{width:1920,height:1080});assert.equal(landscape.station.vertical,false)
for(const fixture of ["recommended","bounded-many"]){for(let step=0;step<1000;step+=1){const s=state(fixture,step/1000);assert.equal(s.cards.length,makeFixture(fixture).length);assert.ok(s.cards.filter(c=>c.visible).length<=16);const ordered=[...s.cards].sort((a,b)=>a.sourceIndex-b.sourceIndex);assert.deepEqual(ordered.map(c=>c.sourceIndex),Array.from({length:ordered.length},(_,i)=>i))}}
const failed=state("mixed-failed",.42);const failedCard=failed.cards.find(c=>c.failed);assert.equal(failedCard.sourceIndex,5);assert.equal(failedCard.id,"strip-frame-06")
const reduced=state("recommended",.63,{reducedMotion:true,selectedIndex:5});assert.equal(reduced.selectedIndex,5);const atStation=reduced.cards.find(c=>c.sourceIndex===5);assert.ok(Math.abs(atStation.stationDistance)<1e-8)
const directed=compileTimeline({mode:"directed",itemCount:8,controls:base});assert.deepEqual(directed.directedPattern,["quick","quick","regular","quick"]);assert.deepEqual(directed.segments.filter(s=>s.kind==="hold").slice(0,4).map(s=>s.pace),["quick","quick","regular","quick"])
const small=state("recommended",.33,{controls:{frameSize:35,gap:8,stationPosition:25,focusLift:0}}),large=state("recommended",.33,{controls:{frameSize:90,gap:80,stationPosition:75,focusLift:50}});assert.notDeepEqual(small.cards.map(c=>[c.x,c.y,c.width,c.height]),large.cards.map(c=>[c.x,c.y,c.width,c.height]));assert.notDeepEqual(small.station,large.station)
const forward=state("recommended",.27),reverse=state("recommended",.73,{direction:"reverse"});const of=[...forward.cards].sort((a,b)=>a.sourceIndex-b.sourceIndex),or=[...reverse.cards].sort((a,b)=>a.sourceIndex-b.sourceIndex);for(let i=0;i<of.length;i+=1)assert.ok(Math.hypot(of[i].x-or[i].x,of[i].y-or[i].y)<1e-6)
assert.ok(Math.abs(sourceVideoTimeSeconds(11000,9.6,true)-1.4)<1e-12)
console.log(JSON.stringify({sceneId:sceneMeta.id,result:"pass",checks:["exact seam","one rests","two scans one direction","portrait column","stable order and failed slot","bounded visibility","keyboard station meaning","directed inspection rhythm","causal controls","reverse retrace","source-video story time"]},null,2))
