import assert from "node:assert/strict"
import {defaultControls,makeFixture,compileTimeline,evaluateScene,sourceVideoTimeSeconds} from "./evaluator.mjs"
import {renderState} from "./raster.mjs"
import {alphaDiagnostics} from "./raster-core.mjs"
const controls=defaultControls()
const evaluate=(fixture="recommended",time=0,width=1920,height=1080,patch={},mode="automatic",direction="forward",reducedMotion=false,selectedIndex=0)=>{const items=makeFixture(fixture);const local={...controls,...patch};const timeline=compileTimeline({mode,itemCount:items.length,controls:local,direction});return evaluateScene({items,controls:local,timeline,timeMs:time*timeline.durationMs,width,height,reducedMotion,selectedIndex})}
const near=(a,b,tolerance=1e-6)=>Math.abs(a-b)<=tolerance
const checkNoOverlap=(state)=>{for(let i=0;i<state.cards.length;i+=1)for(let j=i+1;j<state.cards.length;j+=1){const a=state.cards[i],b=state.cards[j];const overlapX=Math.min(a.cellX+a.width,b.cellX+b.width)-Math.max(a.cellX,b.cellX);const overlapY=Math.min(a.cellY+a.height,b.cellY+b.height)-Math.max(a.cellY,b.cellY);assert.ok(overlapX<=1e-6||overlapY<=1e-6,`overlap ${a.id} ${b.id}`)}}
for(const fixture of ["one","two","recommended","bounded-many","mixed-failed"])for(const [w,h] of [[1920,1080],[1080,1920],[1080,1080],[1080,1350]]){const state=evaluate(fixture,.43,w,h);assert.equal(state.cards.length,makeFixture(fixture).length);assert.ok(state.cards.every(card=>card.visible));checkNoOverlap(state);assert.deepEqual(state.cards.map(card=>card.sourceIndex),Array.from({length:state.cards.length},(_,i)=>i));assert.ok(state.cards.every(card=>card.artworkOpacity===1&&card.artworkFilter==="none"&&card.blendMode==="normal"&&card.scale===1))}
const start=evaluate("bounded-many",0),end=evaluate("bounded-many",1);for(let i=0;i<start.cards.length;i+=1){assert.ok(near(start.cards[i].x,end.cards[i].x));assert.ok(near(start.cards[i].y,end.cards[i].y));assert.ok(near(start.cards[i].width,end.cards[i].width));assert.ok(near(start.cards[i].height,end.cards[i].height))}assert.equal(start.focus.kind,end.focus.kind);assert.ok(near(start.focus.x,end.focus.x)&&near(start.focus.y,end.focus.y)&&near(start.focus.width,end.focus.width)&&near(start.focus.height,end.focus.height))
const stableA=evaluate("recommended",.12),stableB=evaluate("recommended",.67);for(let i=0;i<stableA.cards.length;i+=1)assert.deepEqual([stableA.cards[i].x,stableA.cards[i].y,stableA.cards[i].width,stableA.cards[i].height],[stableB.cards[i].x,stableB.cards[i].y,stableB.cards[i].width,stableB.cards[i].height])
const one=evaluate("one",.2),two=evaluate("two",.2);assert.equal(one.layout.columns,1);assert.equal(two.layout.columns,2);assert.ok(near(one.cards[0].x,960,1));assert.ok(two.cards[0].x<960&&two.cards[1].x>960)
const many=evaluate("bounded-many",.4);assert.equal(many.cards.length,24);assert.equal(many.layout.traversalOrder.length,24);assert.equal(new Set(many.layout.traversalOrder).size,24)
const failed=evaluate("mixed-failed",.4);assert.equal(failed.cards[6].failed,true);assert.equal(failed.cards[6].sourceIndex,6);assert.deepEqual(failed.cards.map(card=>card.id),makeFixture("mixed-failed").map(item=>item.id))
const row=evaluate("mixed-failed",.37,1080,1350,{traversal:"row-major"});const snake=evaluate("mixed-failed",.37,1080,1350,{traversal:"serpentine"});const column=evaluate("mixed-failed",.37,1080,1350,{traversal:"column-major"});assert.deepEqual(row.layout.traversalOrder.slice(0,4),[0,1,2,3]);assert.notDeepEqual(snake.layout.traversalOrder,row.layout.traversalOrder);assert.notDeepEqual(column.layout.traversalOrder,row.layout.traversalOrder);for(let i=0;i<row.cards.length;i+=1)assert.deepEqual([row.cards[i].x,row.cards[i].y],[snake.cards[i].x,snake.cards[i].y])
const columns2=evaluate("recommended",.2,1920,1080,{columns:"2"}),columns6=evaluate("recommended",.2,1920,1080,{columns:"6"});assert.notEqual(columns2.layout.columns,columns6.layout.columns);assert.notEqual(columns2.cards[0].width,columns6.cards[0].width)
const gap10=evaluate("recommended",.2,1920,1080,{gutter:10}),gap72=evaluate("recommended",.2,1920,1080,{gutter:72});assert.notEqual(gap10.cards[1].x-gap10.cards[0].x,gap72.cards[1].x-gap72.cards[0].x)
const margin4=evaluate("recommended",.2,1920,1080,{sheetMargin:4}),margin16=evaluate("recommended",.2,1920,1080,{sheetMargin:16});assert.notEqual(margin4.layout.gridBounds.width,margin16.layout.gridBounds.width)
const labelsBoth=evaluate("recommended",.2,1920,1080,{labels:"both"}),labelsNone=evaluate("recommended",.2,1920,1080,{labels:"none"});assert.equal(labelsNone.controls.labels,"none");assert.ok(labelsNone.cards.every(card=>card.labelHeight===0));for(let i=0;i<labelsBoth.cards.length;i+=1)assert.deepEqual([labelsBoth.cards[i].x,labelsBoth.cards[i].y,labelsBoth.cards[i].width,labelsBoth.cards[i].height],[labelsNone.cards[i].x,labelsNone.cards[i].y,labelsNone.cards[i].width,labelsNone.cards[i].height])
let finale=null;for(let i=0;i<=1000;i+=1){const state=evaluate("recommended",i/1000);if(state.focus.kind==="whole-set"){finale=state;break}}assert.ok(finale);assert.ok(finale.focus.width>=finale.layout.gridBounds.width)
const reducedA=evaluate("recommended",.1,1920,1080,{},"automatic","forward",true,7),reducedB=evaluate("recommended",.8,1920,1080,{},"automatic","forward",true,7);assert.equal(reducedA.focus.kind,"cell");assert.equal(reducedA.selectedIndex,7);assert.deepEqual(reducedA.focus,reducedB.focus)
const forward=evaluate("recommended",.27,1920,1080,{},"automatic","forward"),reverse=evaluate("recommended",.73,1920,1080,{},"automatic","reverse");assert.ok(near(forward.focus.x,reverse.focus.x)&&near(forward.focus.y,reverse.focus.y)&&near(forward.focus.width,reverse.focus.width)&&near(forward.focus.height,reverse.focus.height))
assert.ok(near(sourceVideoTimeSeconds(12500,11.2,true),1.3));assert.equal(sourceVideoTimeSeconds(12500,11.2,false),11.2)
const raster=renderState(evaluate("recommended",.43,960,540),{width:960,height:540});const alpha=alphaDiagnostics(raster);assert.equal(alpha.opaque,960*540);assert.equal(alpha.zeroAlpha,0);assert.equal(alpha.partialAlpha,0)
let rejected=false;try{const items=Array.from({length:25},(_,i)=>({id:`x-${i}`,sourceIndex:i,ratio:1,fit:"contain",caption:"",failed:false,type:"image"}));const timeline=compileTimeline({itemCount:25});evaluateScene({items,controls,timeline,timeMs:0,width:100,height:100})}catch{rejected=true}assert.equal(rejected,true)
console.log(JSON.stringify({sceneId:"contact-sheet",result:"pass",checks:["exact seam","stable whole-set topology","one/two sparse sheets","all 24 visible and ordered","mixed ratios and failed slot","row/serpentine/column traversal","causal discrete and continuous controls","whole-set finale","reduced-motion static mark","reverse retrace","opaque surface","source-video story time"]},null,2))
