import assert from "node:assert/strict"
import {sceneMeta,canonicalTimes,makeFixture,defaultControls,compileTimeline,evaluateScene,sourceVideoTimeSeconds} from "./evaluator.mjs"
const base=defaultControls();const state=(fixture,time,options={})=>{const items=makeFixture(fixture),controls={...base,...(options.controls??{})},timeline=compileTimeline({mode:options.mode??"automatic",itemCount:items.length,controls,direction:options.direction??"forward"});return evaluateScene({items,controls,timeline,timeMs:time*timeline.durationMs,width:options.width??1920,height:options.height??1080,reducedMotion:options.reducedMotion??false,debug:false,selectedIndex:options.selectedIndex??0})}
for(const fixture of ["one","two","recommended","bounded-many","mixed-failed"]){const start=state(fixture,0),end=state(fixture,1);assert.deepEqual(start.cards.map(c=>c.id),end.cards.map(c=>c.id));for(let i=0;i<start.cards.length;i+=1){assert.ok(Math.hypot(start.cards[i].x-end.cards[i].x,start.cards[i].y-end.cards[i].y)<1e-7);assert.ok(Math.abs(start.cards[i].angle-end.cards[i].angle)<1e-10);assert.ok(Math.abs(start.cards[i].currentLength-end.cards[i].currentLength)<1e-7);assert.equal(start.cards[i].pivotX,end.cards[i].pivotX);assert.equal(start.cards[i].artworkOpacity,1);assert.equal(start.cards[i].artworkFilter,"none")}}
for(const fixture of ["one","two","recommended","bounded-many"]){for(const [width,height] of [[1920,1080],[1080,1920],[1080,1080],[1080,1350]])for(const time of canonicalTimes){const s=state(fixture,time,{width,height});assert.deepEqual(s.collisionPairs,[],`${fixture} ${width}x${height} t=${time} collision`)}}
const one=state("one",.5);assert.equal(one.cards.length,1);assert.ok(Math.abs(one.cards[0].pivotX-960)<1e-9);assert.ok(Math.abs(one.cards[0].angle)<.08)
const two=state("two",.5);const orderedTwo=[...two.cards].sort((a,b)=>a.sourceIndex-b.sourceIndex);assert.ok(orderedTwo[0].pivotX<960&&orderedTwo[1].pivotX>960)
const low=state("recommended",.37,{controls:{impulseStrength:0}}),high=state("recommended",.37,{controls:{impulseStrength:65,damping:35}});assert.ok(Math.max(...low.cards.map(c=>Math.abs(c.angle)))<1e-12);assert.ok(Math.max(...high.cards.map(c=>Math.abs(c.angle)))>.01)
const dampLow=state("recommended",.68,{controls:{damping:35,impulseStrength:50}}),dampHigh=state("recommended",.68,{controls:{damping:92,impulseStrength:50}});assert.ok(Math.max(...dampHigh.cards.map(c=>Math.abs(c.angle)))<Math.max(...dampLow.cards.map(c=>Math.abs(c.angle))))
const reducedA=state("recommended",.2,{reducedMotion:true,selectedIndex:2}),reducedB=state("recommended",.7,{reducedMotion:true,selectedIndex:2});for(let i=0;i<reducedA.cards.length;i+=1){assert.ok(Math.hypot(reducedA.cards[i].x-reducedB.cards[i].x,reducedA.cards[i].y-reducedB.cards[i].y)<1e-9);assert.ok(Math.abs(reducedA.cards[i].angle-reducedB.cards[i].angle)<1e-12);assert.ok(Math.abs(reducedA.cards[i].currentLength-reducedB.cards[i].currentLength)<1e-9)}
const forward=state("recommended",.31),reverse=state("recommended",.69,{direction:"reverse"});for(let i=0;i<forward.cards.length;i+=1)assert.ok(Math.hypot(forward.cards[i].x-reverse.cards[i].x,forward.cards[i].y-reverse.cards[i].y)<1e-6)
assert.ok(Math.abs(sourceVideoTimeSeconds(10000,8.8,true)-1.2)<1e-12)
for(let frame=0;frame<2000;frame+=1){const s=state("bounded-many",frame/2000);assert.equal(s.cards.length,10)}
console.log(JSON.stringify({sceneId:sceneMeta.id,result:"pass",checks:["exact seam","fixed pivots and lengths","collision-free canonical matrix","one/two/many","causal impulse and damping","reduced motion","reverse retrace","source-video story time","bounded 2,000-frame observation"]},null,2))
