const DAY_MS=24*60*60*1000
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v))
const mod=(v,d)=>((v%d)+d)%d
const smoother=v=>{const x=clamp(v,0,1);return x*x*x*(x*(x*6-15)+10)}
function finite(value,label,min,max){if(!Number.isFinite(value)||value<min||value>max)throw new RangeError(`${label}:finite-number-required`);return value}
function validateItem(item){if(!item||typeof item.id!=='string'||!item.id)throw new TypeError('source-required');finite(Number(item.ratio),'ratio',.05,20);return{...item,caption:typeof item.caption==='string'?item.caption:'',kind:item.kind==='video'?'video':'image',failed:Boolean(item.failed)}}
function params(input={}){const direction=input.direction??'forward';if(!['forward','reverse'].includes(direction))throw new TypeError('direction:unsupported');const fit=input.fit??'contain';if(!['contain','cover'].includes(fit))throw new TypeError('fit:unsupported');return{separation:finite(Number(input.separation??.14),'separation',.04,.22),viewAngleDeg:finite(Number(input.viewAngleDeg??7),'viewAngleDeg',0,12),openMs:finite(Number(input.openMs??900),'openMs',300,4000),holdMs:finite(Number(input.holdMs??1400),'holdMs',300,6000),closeMs:finite(Number(input.closeMs??900),'closeMs',300,4000),direction,fit,labels:input.labels!==false,showGuides:input.showGuides!==false,background:input.background??'transparent'}}
export function presentPlanes(item,apparatus={}){const source=validateItem(item);const list=[];if(apparatus.worldBacking)list.push({id:'world-backing',kind:'world'});if(apparatus.matte)list.push({id:'matte',kind:'apparatus'});list.push({id:'source',kind:'source',sourceId:source.id});if(apparatus.guides)list.push({id:'guides',kind:'apparatus'});if(source.caption.trim())list.push({id:'caption',kind:'apparatus'});return list}
function phrase(start,scale,p){const open=p.openMs/scale,hold=p.holdMs/scale,close=p.closeMs/scale;return[{id:'opening',kind:'travel',startMs:start,endMs:start+open,from:0,to:1},{id:'open-hold',kind:'hold',startMs:start+open,endMs:start+open+hold,from:1,to:1},{id:'closing',kind:'travel',startMs:start+open+hold,endMs:start+open+hold+close,from:1,to:0}]}
export function compileAnatomyTimeline({mode='automatic',item,apparatus={},parameters:input={},fixedDurationMs=0}){if(!['automatic','fixed-duration','directed'].includes(mode))throw new TypeError('mode:unsupported');const p=params(input),planes=presentPlanes(item,apparatus);const readingAllowance=Math.max(0,planes.length-1)*120;const adjusted={...p,holdMs:p.holdMs+readingAllowance};const base=adjusted.openMs+adjusted.holdMs+adjusted.closeMs;let segments=[];if(mode==='fixed-duration'){const floor=600+planes.length*180;const duration=finite(Number(fixedDurationMs),'fixedDurationMs',floor,DAY_MS);const scale=base/duration;segments=phrase(0,scale,adjusted);segments.at(-1).endMs=duration}else{const scales=mode==='directed'?[2,2,1,2]:[1];let elapsed=0;for(let i=0;i<scales.length;i++){const prefix=mode==='directed'?['fast-1','fast-2','regular','fast-close'][i]:'automatic';const part=phrase(elapsed,scales[i],adjusted).map(s=>({...s,id:`${prefix}:${s.id}`,paceScale:scales[i]}));segments.push(...part);elapsed=part.at(-1).endMs}}return Object.freeze({mode,durationMs:mode==='fixed-duration'?Number(fixedDurationMs):segments.at(-1).endMs,parameters:Object.freeze(p),planes:Object.freeze(planes.map(Object.freeze)),segments:Object.freeze(segments.map(Object.freeze))})}
function openPose(plane,index,count,p,width,height){const landscape=width>=height;const centred=index-(count-1)/2;const span=Math.min(width,height)*p.separation;return{x:landscape?centred*span*.62:centred*span*.22,y:landscape?centred*span*.16:centred*span*.62,z:centred*span,rotateX:landscape?p.viewAngleDeg:-p.viewAngleDeg*.35,rotateY:landscape?-p.viewAngleDeg*.5:p.viewAngleDeg*.35,opacity:plane.id==='world-backing'?.72:1}}
export function evaluateSlideAnatomy({item,timeline,timeMs,stageWidth,stageHeight,reducedMotion=false}){const source=validateItem(item);finite(Number(timeMs),'timeMs',-DAY_MS,DAY_MS*2);finite(Number(stageWidth),'stageWidth',1,16384);finite(Number(stageHeight),'stageHeight',1,16384);if(!timeline?.planes?.length)throw new TypeError('timeline-required');const p=timeline.parameters;let openness,velocity=0,segmentId,state;if(reducedMotion){openness=1;segmentId='reduced-motion';state='open'}else{const local=mod(timeMs,timeline.durationMs),segment=timeline.segments.find(s=>local<s.endMs)??timeline.segments.at(-1),progress=(local-segment.startMs)/Math.max(1,segment.endMs-segment.startMs),amount=segment.kind==='travel'?smoother(progress):0;openness=segment.from+(segment.to-segment.from)*amount;velocity=segment.kind==='travel'?(segment.to-segment.from)/(segment.endMs-segment.startMs):0;segmentId=segment.id;state=segment.id.includes('opening')?'opening':segment.id.includes('closing')?'closing':'open'}if(p.direction==='reverse'){openness=1-openness;velocity=-velocity;state=state==='opening'?'closing':state==='closing'?'opening':openness===1?'open':'closed'}if(openness===0&&state!=='opening'&&state!=='closing')state='closed';const planes=timeline.planes.map((plane,index)=>{const open=openPose(plane,index,timeline.planes.length,p,stageWidth,stageHeight);return{id:plane.id,kind:plane.kind,sourceId:plane.sourceId,x:open.x*openness,y:open.y*openness,z:open.z*openness,rotateX:open.rotateX*openness,rotateY:open.rotateY*openness,opacity:1+(open.opacity-1)*openness}});return{state,openness,velocity,segmentId,planes,source:{id:source.id,failed:source.failed},render:{artworkOpacity:1,artworkFilter:'none',blendMode:'normal',fit:p.fit,transparentWorld:p.background==='transparent'}}}
export function videoStoryTimeMs(timeMs,durationMs,loop=true){finite(Number(timeMs),'timeMs',-DAY_MS,DAY_MS*2);finite(Number(durationMs),'durationMs',1,DAY_MS);return loop?mod(timeMs,durationMs):clamp(timeMs,0,durationMs)}
