// Adapted from pitch.dog Drift @ 340b5f631c9147890bc775c86a71af315dd17929
// Copyright (C) 2026 pitch.dog and contributors. AGPL-3.0-or-later.
// Generated by scripts/native/generate-drift-backgrounds.py; do not hand-edit.
#include <metal_stdlib>
#include <CoreImage/CoreImage.h>
using namespace metal;
float driftMod(float x, float y) { return x - y * floor(x/y); }
float2 driftMod(float2 x, float y) { return x - y * floor(x/y); }
float2 driftMod(float2 x, float2 y) { return x - y * floor(x/y); }
float3 driftToLinear(float3 c) { return select(pow((c + 0.055) / 1.055, float3(2.4)), c / 12.92, c <= 0.04045); }
float3 driftToSRGB(float3 c) { c = max(c, float3(0)); return select(1.055 * pow(c, float3(1.0/2.4)) - 0.055, c * 12.92, c <= 0.0031308); }
struct DriftShader {

  float2 vUv;

  float2 uResolution;
  float3 uColorA;
  float3 uColorB;
  float3 uAccent;
  float uMode;
  float uIntensity;
  float uMotion;
  float uGrain;
  float uGrainFrame;
  float uGrainSeed;
  float uVignette;
  float uPhase;
  float uSeed;
  float uOpacity;

  const float PI = 3.141592653589793;
  const float TAU = 6.283185307179586;
  const float BACKGROUND_VARIANT_COUNT = 8.0;
  const float BACKGROUND_ATLAS_SEED_BASE = 10000.0;

  float hash12(float2 p) {
    float3 p3 = fract(float3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
  }

  float valueNoise(float2 p) {
    float2 cell = floor(p);
    float2 local = fract(p);
    local = local * local * (3.0 - 2.0 * local);
    float a = hash12(cell);
    float b = hash12(cell + float2(1.0, 0.0));
    float c = hash12(cell + float2(0.0, 1.0));
    float d = hash12(cell + float2(1.0, 1.0));
    return mix(mix(a, b, local.x), mix(c, d, local.x), local.y);
  }

  float grainHash12(float2 p) {
    float2 seedShift = float2(uGrainSeed * 0.754877666, uGrainSeed * 0.569840296);
    float3 p3 = fract(float3((p + seedShift).xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
  }

  float grainValueNoise(float2 p, float frame) {
    float2 cell = floor(p);
    float2 local = fract(p);
    float2 ease = local * local * (3.0 - 2.0 * local);
    float2 frameOffset = float2(frame * 19.19, frame * 73.73);
    float a = grainHash12(cell + frameOffset);
    float b = grainHash12(cell + float2(1.0, 0.0) + frameOffset);
    float c = grainHash12(cell + float2(0.0, 1.0) + frameOffset);
    float d = grainHash12(cell + float2(1.0, 1.0) + frameOffset);
    return mix(mix(a, b, ease.x), mix(c, d, ease.x), ease.y);
  }

  float filmGrain(float2 pixel, float frame) {
    // Fine emulsion must read as texture, never as a field of square tiles.
    // A restrained larger stock keeps the plate visible after downsampling;
    // the fine stock carries most of the energy at native export resolution.
    float fine = grainValueNoise(pixel / 1.35, frame);
    float clump = grainValueNoise(pixel / 3.4 + 41.0, frame + 17.0);
    return ((fine - 0.5) * 0.76 + (clump - 0.5) * 0.24) * 2.0;
  }

  float fbm(float2 p) {
    float value = 0.0;
    float amplitude = 0.5;
    float2x2 turn = float2x2(float2(0.80, -0.60), float2( 0.60, 0.80));
    for (int octave = 0; octave < 4; octave += 1) {
      value += valueNoise(p) * amplitude;
      p = turn * p * 2.03 + float2(17.17, 9.23);
      amplitude *= 0.5;
    }
    return value;
  }

  float ridgedFbm(float2 p) {
    float value = 0.0;
    float amplitude = 0.55;
    float2x2 turn = float2x2(float2(0.86, -0.51), float2( 0.51, 0.86));
    for (int octave = 0; octave < 4; octave += 1) {
      float ridge = 1.0 - abs(valueNoise(p) * 2.0 - 1.0);
      value += ridge * ridge * amplitude;
      p = turn * p * 2.07 + float2(11.03, 23.61);
      amplitude *= 0.48;
    }
    return value;
  }

  float2x2 rotate2d(float angle) {
    float c = cos(angle);
    float s = sin(angle);
    return float2x2(float2(c, -s), float2( s, c));
  }

  float softBlob(float2 p, float2 center, float radius) {
    return 1.0 - smoothstep(0.0, radius, length(p - center));
  }

  float softEllipse(float2 p, float2 center, float2 radius, float feather) {
    float distanceToCenter = length((p - center) / max(radius, float2(0.0001)));
    return 1.0 - smoothstep(1.0 - feather, 1.0 + feather, distanceToCenter);
  }

  float softRing(float2 p, float2 center, float2 radius, float width, float feather) {
    float distanceToRing = abs(length((p - center) / max(radius, float2(0.0001))) - 1.0);
    return 1.0 - smoothstep(width, width + feather, distanceToRing);
  }

  float softBand(float coordinate, float center, float halfWidth, float feather) {
    return 1.0 - smoothstep(halfWidth, halfWidth + feather, abs(coordinate - center));
  }

  float gridLine(float coordinate, float frequency, float width) {
    float cell = abs(fract(coordinate * frequency) - 0.5);
    return smoothstep(0.5 - width, 0.5, cell);
  }

  float4 render() {
    float2 uv = vUv;
    float2 p = uv - 0.5;
    float aspect = uResolution.x / max(1.0, uResolution.y);
    p.x *= aspect;

    // Seeds below 10,000 keep the old background grammar. Atlas studies live
    // in a reserved range, so schema-v1 project files remain readable and old
    // theme seeds still resolve to their original composition (variant zero).
    float normalizedSeed = max(0.0, floor(uSeed + 0.5));
    float atlasEnabled = step(BACKGROUND_ATLAS_SEED_BASE, normalizedSeed);
    float atlasAddress = max(0.0, normalizedSeed - BACKGROUND_ATLAS_SEED_BASE);
    float atlasVariant = mix(0.0, driftMod(atlasAddress, BACKGROUND_VARIANT_COUNT), atlasEnabled);
    float variation = mix(normalizedSeed, floor(atlasAddress / BACKGROUND_VARIANT_COUNT), atlasEnabled);

    float2 variationKey = float2(variation * 0.071 + 3.17, variation * 0.113 + 9.41);
    float2 seedOffset = float2(hash12(variationKey), hash12(variationKey + 31.7)) - 0.5;
    float seedAngle = (hash12(variationKey + 67.3) - 0.5) * TAU;
    float seedScale = mix(0.82, 1.24, hash12(variationKey + 97.1));
    float2 closedDrift = float2(cos(uPhase), sin(uPhase)) * uMotion;
    float2 closedDriftTwo = float2(cos(uPhase * 2.0 + 1.7), sin(uPhase * 2.0 + 1.7)) * uMotion;
    float2 q = rotate2d(seedAngle * 0.24) * p * seedScale + seedOffset * 0.34;
    float wave = sin(uPhase) * uMotion;
    float3 color = uColorA;


    if (uMode < 0.5) {
      // solid-0 · Pure field / legacy solid
      if (atlasVariant < 0.5) {
        color = uColorA;
      // solid-1 · Projector wash
      } else if (atlasVariant < 1.5) {
        float2 center = float2(aspect * 0.42, -0.24) + seedOffset * 0.18 + closedDrift * 0.06;
        float wash = softEllipse(p, center, float2(0.94, 0.82), 0.34);
        float floorLight = smoothstep(-0.62, 0.48, p.y + wave * 0.04);
        color = mix(uColorA, uColorB, floorLight * 0.24);
        color = mix(color, uAccent, wash * 0.44 * uIntensity);
      // solid-2 · Edge light
      } else if (atlasVariant < 2.5) {
        float side = step(0.5, hash12(variationKey + 12.0));
        float edgeCoordinate = mix(p.x + aspect * 0.56, aspect * 0.56 - p.x, side);
        float edge = 1.0 - smoothstep(0.0, 0.78, max(0.0, edgeCoordinate));
        float verticalFade = 1.0 - smoothstep(0.42, 0.92, abs(p.y + seedOffset.y * 0.2));
        color = mix(uColorA, uColorB, edge * 0.2 * uIntensity);
        color = mix(color, uAccent, edge * verticalFade * 0.52 * uIntensity);
      // solid-3 · Duotone floor
      } else if (atlasVariant < 3.5) {
        float horizonCoordinate = p.y + 0.2 + sin(p.x * 1.7 + seedAngle) * 0.035 + wave * 0.05;
        float floorMask = smoothstep(-0.18, 0.24, horizonCoordinate);
        float seam = 1.0 - smoothstep(0.0, 0.18, abs(horizonCoordinate));
        color = mix(uColorA, uColorB, floorMask * 0.72 * uIntensity);
        color = mix(color, uAccent, seam * 0.14 * uIntensity);
      // solid-4 · Soft burn
      } else if (atlasVariant < 4.5) {
        float reaction = fbm(q * 2.15 + closedDrift * 0.18);
        float burnBody = softEllipse(q, seedOffset * 0.22 + closedDriftTwo * 0.05, float2(0.58, 0.76), 0.3);
        float burn = smoothstep(0.28, 0.78, burnBody + (reaction - 0.5) * 0.46);
        float reactionEdge = 1.0 - smoothstep(0.0, 0.12, abs(burnBody + (reaction - 0.5) * 0.46 - 0.52));
        color = mix(uColorA, uColorB, burn * 0.58 * uIntensity);
        color = mix(color, uAccent, reactionEdge * 0.42 * uIntensity);
      // solid-5 · Paper tooth
      } else if (atlasVariant < 5.5) {
        float longFibre = sin((q.y + sin(q.x * 13.0) * 0.014) * 720.0) * 0.5 + 0.5;
        float crossFibre = sin((q.x + sin(q.y * 9.0) * 0.01) * 430.0) * 0.5 + 0.5;
        float exposure = smoothstep(-0.52, 0.58, q.y + seedOffset.x * 0.12);
        color = mix(uColorA, uColorB, exposure * 0.2 * uIntensity);
        color += (longFibre - 0.5) * 0.026 * uIntensity;
        color += (crossFibre - 0.5) * 0.012 * uIntensity;
      // solid-6 · Low halo
      } else if (atlasVariant < 6.5) {
        float2 center = float2(seedOffset.x * 0.22, -0.38 + seedOffset.y * 0.08) + closedDrift * 0.035;
        float body = softEllipse(p, center, float2(0.72, 0.38), 0.36);
        float ring = softRing(p, center, float2(0.66, 0.34), 0.1, 0.18);
        color = mix(uColorA, uColorB, body * 0.34 * uIntensity);
        color = mix(color, uAccent, ring * 0.26 * uIntensity);
      // solid-7 · Night exposure
      } else {
        float exposure = smoothstep(-0.72, 0.72, p.y + p.x * 0.08);
        float longBand = softBand(p.y + sin(p.x * 1.5 + seedAngle) * 0.035, -0.18 + wave * 0.05, 0.12, 0.3);
        color = mix(uColorA, uColorB, exposure * 0.36 * uIntensity);
        color = mix(color, uAccent, longBand * 0.34 * uIntensity);
      }



    } else if (uMode < 1.5) {
      // gradient-0 · Legacy horizon
      if (atlasVariant < 0.5) {
        float gradient = smoothstep(-0.65, 0.72, p.y + p.x * 0.42 + wave * 0.08);
        color = mix(uColorA, uColorB, gradient);
        color = mix(color, uAccent, softBlob(p, float2(0.35 + cos(uPhase) * 0.08, -0.3), 0.7) * 0.32 * uIntensity);
      // gradient-1 · Horizon melt
      } else if (atlasVariant < 1.5) {
        float weather = fbm(q * 1.72 + closedDrift * 0.14);
        float horizonCoordinate = p.y + (weather - 0.5) * 0.38 + sin(p.x * 2.1 + seedAngle) * 0.055;
        float horizon = smoothstep(-0.2, 0.22, horizonCoordinate);
        float seam = 1.0 - smoothstep(0.0, 0.16, abs(horizonCoordinate));
        color = mix(uColorA, uColorB, horizon);
        color = mix(color, uAccent, seam * 0.26 * uIntensity);
      // gradient-2 · Diagonal weather
      } else if (atlasVariant < 2.5) {
        float2 diagonal = rotate2d(seedAngle * 0.22 + 0.62) * p;
        float pressure = fbm(q * 1.34 + closedDriftTwo * 0.12);
        float front = smoothstep(-0.66, 0.66, diagonal.y + (pressure - 0.5) * 0.58);
        float cloudEdge = smoothstep(0.48, 0.78, pressure);
        color = mix(uColorA, uColorB, front);
        color = mix(color, uAccent, cloudEdge * 0.24 * uIntensity);
      // gradient-3 · Radial dusk
      } else if (atlasVariant < 3.5) {
        float2 center = seedOffset * 0.24 + closedDrift * 0.055;
        float radius = length(p - center);
        float dusk = smoothstep(0.06, 1.05, radius);
        float afterglow = 1.0 - smoothstep(0.0, 0.68, radius);
        color = mix(uColorB, uColorA, dusk);
        color = mix(color, uAccent, afterglow * 0.48 * uIntensity);
      // gradient-4 · Prism bands
      } else if (atlasVariant < 4.5) {
        float2 prism = rotate2d(seedAngle * 0.18 + 0.32) * p;
        float drift = sin(uPhase + seedAngle) * 0.08 * uMotion;
        float bandA = softBand(prism.x, -0.34 + drift, 0.18, 0.24);
        float bandB = softBand(prism.x, 0.02 - drift * 0.5, 0.16, 0.22);
        float bandC = softBand(prism.x, 0.38 + drift * 0.3, 0.18, 0.24);
        float baseGradient = smoothstep(-0.7, 0.7, prism.y);
        color = mix(uColorA, uColorB, baseGradient * 0.72);
        color = mix(color, uColorB, bandA * 0.32 * uIntensity);
        color = mix(color, uAccent, bandB * 0.46 * uIntensity);
        color += uAccent * bandC * 0.08 * uIntensity;
      // gradient-5 · Twin suns
      } else if (atlasVariant < 5.5) {
        float horizon = smoothstep(-0.62, 0.68, p.y + p.x * 0.12);
        float2 sunA = float2(-aspect * 0.25, -0.12) + seedOffset * 0.12 + closedDrift * 0.045;
        float2 sunB = float2(aspect * 0.3, 0.06) - seedOffset * 0.1 + closedDriftTwo * 0.04;
        float a = softEllipse(p, sunA, float2(0.46, 0.46), 0.38);
        float b = softEllipse(p, sunB, float2(0.34, 0.34), 0.42);
        color = mix(uColorA, uColorB, horizon);
        color = mix(color, uAccent, max(a * 0.44, b * 0.34) * uIntensity);
      // gradient-6 · Split signal
      } else if (atlasVariant < 6.5) {
        float2 signal = rotate2d(seedAngle * 0.16 + 0.78) * p;
        float interference = fbm(q * 2.0 + closedDrift * 0.12) - 0.5;
        float splitCoordinate = signal.x + interference * 0.17;
        float split = smoothstep(-0.08, 0.08, splitCoordinate);
        float seam = 1.0 - smoothstep(0.0, 0.1, abs(splitCoordinate));
        color = mix(uColorA, uColorB, split);
        color = mix(color, uAccent, seam * 0.48 * uIntensity);
      // gradient-7 · Road mirage
      } else {
        float horizonCoordinate = p.y + 0.12 + sin(p.x * 1.8 + seedAngle) * 0.025;
        float horizon = smoothstep(-0.16, 0.2, horizonCoordinate);
        float mirageWindow = smoothstep(-0.34, -0.08, p.y) * (1.0 - smoothstep(0.08, 0.32, p.y));
        float ripples = sin((p.y + 0.22) * 92.0 + sin(p.x * 5.0) * 2.0 + sin(uPhase) * 2.4) * 0.5 + 0.5;
        color = mix(uColorA, uColorB, horizon);
        color = mix(color, uAccent, ripples * mirageWindow * 0.25 * uIntensity);
      }



    } else if (uMode < 2.5) {
      // aura-0 · Orbiting bloom / legacy aura
      if (atlasVariant < 0.5) {
        float2 centerA = float2(cos(uPhase) * 0.34, sin(uPhase) * 0.22);
        float2 centerB = float2(cos(uPhase + 2.1) * 0.42, sin(uPhase + 1.4) * 0.3);
        float a = softBlob(p, centerA, 0.72);
        float b = softBlob(p, centerB, 0.62);
        color = mix(uColorA, uColorB, a * 0.72 * uIntensity);
        color = mix(color, uAccent, b * 0.48 * uIntensity);
      // aura-1 · Projector halo
      } else if (atlasVariant < 1.5) {
        float2 center = seedOffset * 0.16 + closedDrift * 0.045;
        float body = softEllipse(p, center, float2(0.78, 0.7), 0.4);
        float halo = softRing(p, center, float2(0.62, 0.56), 0.13, 0.22);
        color = mix(uColorA, uColorB, body * 0.34 * uIntensity);
        color = mix(color, uAccent, halo * 0.44 * uIntensity);
      // aura-2 · Aurora veil
      } else if (atlasVariant < 2.5) {
        float weather = fbm(float2(q.x * 1.2, q.y * 0.72) + closedDrift * 0.16);
        float veilA = sin((q.x + weather * 0.42) * 7.2 + sin(uPhase) * 0.7) * 0.5 + 0.5;
        float veilB = sin((q.x - weather * 0.28) * 10.4 - sin(uPhase * 2.0) * 0.45 + 1.8) * 0.5 + 0.5;
        veilA = smoothstep(0.48, 0.86, veilA) * (1.0 - smoothstep(0.36, 0.96, abs(q.y)));
        veilB = smoothstep(0.58, 0.9, veilB) * (1.0 - smoothstep(0.28, 0.9, abs(q.y + 0.12)));
        color = mix(uColorA, uColorB, veilA * 0.62 * uIntensity);
        color = mix(color, uAccent, veilB * 0.44 * uIntensity);
      // aura-3 · Stained light
      } else if (atlasVariant < 3.5) {
        float irregularity = fbm(q * 1.8 + closedDriftTwo * 0.12) - 0.5;
        float paneA = softEllipse(p, float2(-aspect * 0.26, -0.12) + seedOffset * 0.14, float2(0.5, 0.68), 0.32);
        float paneB = softEllipse(p, float2(aspect * 0.2, 0.18) - seedOffset * 0.12, float2(0.52, 0.56), 0.34);
        float paneC = softEllipse(p, float2(0.06, -0.34) + closedDrift * 0.035, float2(0.4, 0.38), 0.38);
        paneA = smoothstep(0.12, 0.88, paneA + irregularity * 0.38);
        paneB = smoothstep(0.12, 0.88, paneB - irregularity * 0.28);
        color = mix(uColorA, uColorB, paneA * 0.62 * uIntensity);
        color = mix(color, uAccent, max(paneB * 0.48, paneC * 0.3) * uIntensity);
      // aura-4 · Liquid caustic
      } else if (atlasVariant < 4.5) {
        float liquid = ridgedFbm(q * 2.75 + closedDrift * 0.24);
        float undertow = fbm(q * 1.05 - closedDriftTwo * 0.1);
        float caustic = smoothstep(0.58, 0.92, liquid);
        color = mix(uColorA, uColorB, undertow * 0.54 * uIntensity);
        color = mix(color, uAccent, caustic * 0.42 * uIntensity);
      // aura-5 · Rose chamber
      } else if (atlasVariant < 5.5) {
        float approach = sin(uPhase) * 0.035 * uMotion;
        float2 leftCenter = float2(-aspect * 0.22 + approach, -0.02) + seedOffset * 0.08;
        float2 rightCenter = float2(aspect * 0.22 - approach, 0.04) - seedOffset * 0.08;
        float left = softEllipse(p, leftCenter, float2(0.5, 0.72), 0.42);
        float right = softEllipse(p, rightCenter, float2(0.5, 0.68), 0.42);
        color = mix(uColorA, uColorB, left * 0.56 * uIntensity);
        color = mix(color, uAccent, right * 0.46 * uIntensity);
      // aura-6 · Ice bloom
      } else if (atlasVariant < 6.5) {
        float2 bloomPoint = q + closedDrift * 0.04;
        float radius = length(bloomPoint);
        float angle = atan2(bloomPoint.y, bloomPoint.x);
        float petals = cos(angle * 6.0 + sin(uPhase) * 0.3 + seedAngle) * 0.5 + 0.5;
        float bloom = 1.0 - smoothstep(0.18, 0.9, radius + petals * 0.22);
        float crystal = smoothstep(0.52, 0.9, ridgedFbm(bloomPoint * 3.1));
        color = mix(uColorA, uColorB, bloom * 0.58 * uIntensity);
        color = mix(color, uAccent, bloom * crystal * 0.38 * uIntensity);
      // aura-7 · Mandorla
      } else {
        float opening = 0.18 + sin(uPhase) * 0.025 * uMotion;
        float left = softEllipse(p, float2(-opening, 0.0) + seedOffset * 0.05, float2(0.62, 0.82), 0.24);
        float right = softEllipse(p, float2(opening, 0.0) - seedOffset * 0.05, float2(0.62, 0.82), 0.24);
        float overlap = left * right;
        float outer = max(left, right);
        color = mix(uColorA, uColorB, outer * 0.36 * uIntensity);
        color = mix(color, uAccent, overlap * 0.58 * uIntensity);
      }



    } else if (uMode < 3.5) {
      // paper-0 · Long fibres / legacy paper
      if (atlasVariant < 0.5) {
        // Anisotropic, seeded value noise reads as stock under resampling;
        // high-frequency sine fibres read as digital contour interference.
        float fibres = valueNoise(float2(p.x * 37.0, p.y * 110.0) + variationKey * 0.31);
        float crossFibres = valueNoise(float2(p.x * 84.0, p.y * 19.0) + variationKey * 0.57);
        float paperCloud = valueNoise(p * 3.4 + variationKey + 91.0);
        color = mix(uColorA, uColorB, smoothstep(-0.45, 0.65, p.y));
        color += (paperCloud - 0.5) * 0.014 * uIntensity;
        color += ((fibres - 0.5) * 0.006 + (crossFibres - 0.5) * 0.004) * uIntensity;
      // paper-1 · Contact sheet
      } else if (atlasVariant < 1.5) {
        // A contact sheet is a quiet registration system, not wire fencing.
        // Keep its cells aligned to the frame and let seed affect only the
        // minute registration offset.
        float grid = max(
          gridLine(uv.x + seedOffset.x * 0.025, 4.0, 0.011),
          gridLine(uv.y + seedOffset.y * 0.025, 6.0, 0.009)
        );
        float emulsion = fbm(q * 4.2 + closedDrift * 0.03);
        color = mix(uColorA, uColorB, smoothstep(-0.6, 0.62, q.y) * 0.42);
        color = mix(color, uAccent, grid * 0.065 * uIntensity);
        color += (emulsion - 0.5) * 0.055 * uIntensity;
      // paper-2 · Risograph cloud
      } else if (atlasVariant < 2.5) {
        float cloudA = fbm(q * 1.62 + closedDrift * 0.08);
        float cloudB = fbm(q * 1.58 - closedDriftTwo * 0.06 + float2(7.4, 2.1));
        float2 screenUv = rotate2d(0.28) * q;
        float dots = sin(screenUv.x * 118.0) * sin(screenUv.y * 118.0) * 0.5 + 0.5;
        float screen = smoothstep(0.42, 0.78, dots);
        color = mix(uColorA, uColorB, smoothstep(0.36, 0.72, cloudA) * 0.6 * uIntensity);
        color = mix(color, uAccent, smoothstep(0.42, 0.76, cloudB) * screen * 0.42 * uIntensity);
      // paper-3 · Linen drift
      } else if (atlasVariant < 3.5) {
        float vertical = sin((q.y + sin(q.x * 11.0) * 0.012) * 690.0) * 0.5 + 0.5;
        float horizontal = sin((q.x + sin(q.y * 9.0) * 0.012) * 510.0) * 0.5 + 0.5;
        float exposure = smoothstep(-0.7, 0.7, q.x * 0.28 + q.y);
        color = mix(uColorA, uColorB, exposure * 0.34);
        color += (vertical - 0.5) * 0.022 * uIntensity;
        color += (horizontal - 0.5) * 0.016 * uIntensity;
      // paper-4 · Newsprint
      } else if (atlasVariant < 4.5) {
        float2 printUv = rotate2d(0.42 + seedAngle * 0.04) * q;
        float dotScreen = sin(printUv.x * 154.0) * sin(printUv.y * 154.0) * 0.5 + 0.5;
        float ink = smoothstep(0.34, 0.78, dotScreen + (fbm(q * 2.0) - 0.5) * 0.24);
        float fold = 1.0 - smoothstep(0.0, 0.07, abs(q.x + seedOffset.x * 0.22));
        color = mix(uColorA, uColorB, ink * 0.38 * uIntensity);
        color = mix(color, uAccent, fold * 0.1 * uIntensity);
      // paper-5 · Silver emulsion
      } else if (atlasVariant < 5.5) {
        float emulsion = fbm(q * 4.8 + closedDrift * 0.035);
        float clump = smoothstep(0.54, 0.82, emulsion);
        float leak = softEllipse(p, float2(aspect * 0.46, -0.28) + seedOffset * 0.1, float2(0.7, 0.8), 0.42);
        float dust = step(0.988, hash12(floor(gl_FragCoord.xy / 3.0) + variationKey));
        color = mix(uColorA, uColorB, clump * 0.48 * uIntensity);
        color = mix(color, uAccent, leak * 0.2 * uIntensity + dust * 0.34 * uIntensity);
      // paper-6 · Halftone field
      } else if (atlasVariant < 6.5) {
        float2 halfUv = rotate2d(0.24 + seedAngle * 0.05) * q * 30.0;
        float2 cell = fract(halfUv) - 0.5;
        float field = smoothstep(-0.72, 0.72, q.y + q.x * 0.18);
        float dotRadius = mix(0.12, 0.42, field);
        float dotMask = 1.0 - smoothstep(dotRadius, dotRadius + 0.07, length(cell));
        color = mix(uColorA, uColorB, field * 0.5);
        color = mix(color, uAccent, dotMask * 0.38 * uIntensity);
      // paper-7 · Dust archive
      } else {
        float column = floor((q.x + 1.7) * 92.0);
        float scratchSeed = hash12(float2(column, variation + 17.0));
        float scratchCoordinate = abs(fract((q.x + seedOffset.x) * 92.0) - 0.5);
        float scratch = (1.0 - smoothstep(0.0, 0.025, scratchCoordinate)) * step(0.9, scratchSeed);
        float dust = step(0.982, hash12(floor(gl_FragCoord.xy / 4.0) + variationKey));
        float exposure = fbm(q * 1.35 + closedDrift * 0.025);
        color = mix(uColorA, uColorB, exposure * 0.34 * uIntensity);
        color = mix(color, uAccent, (scratch * 0.22 + dust * 0.32) * uIntensity);
      }



    } else if (uMode < 4.5) {
      // void-0 · Breathing slit / legacy void
      if (atlasVariant < 0.5) {
        float slit = exp(-abs(p.x + sin(p.y * 2.4 + uPhase) * 0.08) * 8.0);
        float pulse = 0.82 + 0.18 * sin(uPhase);
        color = mix(uColorA, uColorB, smoothstep(-0.4, 0.5, p.y) * 0.36);
        color = mix(color, uAccent, slit * pulse * 0.28 * uIntensity);
      // void-1 · Eclipse
      } else if (atlasVariant < 1.5) {
        float2 center = seedOffset * 0.18 + closedDrift * 0.035;
        float radius = length(p - center);
        float body = 1.0 - smoothstep(0.34, 0.37, radius);
        float corona = 1.0 - smoothstep(0.0, 0.1, abs(radius - 0.39));
        float distantGlow = 1.0 - smoothstep(0.2, 0.86, radius);
        color = mix(uColorA, uColorB, distantGlow * 0.22 * uIntensity);
        color = mix(color, uAccent, corona * 0.42 * uIntensity);
        color = mix(color, uColorA, body * 0.94);
      // void-2 · Ember smoke
      } else if (atlasVariant < 2.5) {
        float smoke = fbm(q * 1.74 + closedDrift * 0.16);
        float plume = smoothstep(0.38, 0.78, smoke - q.y * 0.14);
        float2 emberCell = floor((q + 1.8) * float2(36.0, 28.0));
        float emberSeed = hash12(emberCell + variationKey);
        float embers = step(0.992, emberSeed) * (0.78 + 0.22 * sin(uPhase * 2.0 + emberSeed * TAU));
        color = mix(uColorA, uColorB, plume * 0.46 * uIntensity);
        color = mix(color, uAccent, embers * 0.76 * uIntensity);
      // void-3 · Abyssal rays
      } else if (atlasVariant < 3.5) {
        float2 source = float2(-aspect * 0.72, 0.72) + seedOffset * 0.12;
        float2 ray = p - source;
        float angle = atan2(ray.y, ray.x);
        float beams = pow(max(0.0, sin(angle * 12.0 + seedAngle + sin(uPhase) * 0.25) * 0.5 + 0.5), 7.0);
        float falloff = 1.0 - smoothstep(0.2, 1.8, length(ray));
        float depthFog = smoothstep(-0.72, 0.54, p.y);
        color = mix(uColorA, uColorB, depthFog * 0.22);
        color = mix(color, uAccent, beams * falloff * 0.36 * uIntensity);
      // void-4 · Mineral fog
      } else if (atlasVariant < 4.5) {
        float strata = ridgedFbm(float2(q.x * 1.7, q.y * 2.5) + closedDrift * 0.12);
        float fog = fbm(q * 1.18 - closedDriftTwo * 0.08);
        float mineral = smoothstep(0.52, 0.88, strata) * smoothstep(0.28, 0.82, fog);
        color = mix(uColorA, uColorB, fog * 0.38 * uIntensity);
        color = mix(color, uAccent, mineral * 0.24 * uIntensity);
      // void-5 · Rain negative
      } else if (atlasVariant < 5.5) {
        float2 rainUv = rotate2d(-0.34 + seedAngle * 0.03) * q;
        float lane = abs(fract((rainUv.x + seedOffset.x) * 84.0) - 0.5);
        float streak = 1.0 - smoothstep(0.012, 0.045, lane);
        float segment = sin(rainUv.y * 38.0 + sin(uPhase) * 2.2 + hash12(float2(floor(rainUv.x * 84.0), variation)) * TAU) * 0.5 + 0.5;
        segment = smoothstep(0.7, 0.94, segment);
        float haze = fbm(q * 1.2 + closedDrift * 0.05);
        color = mix(uColorA, uColorB, haze * 0.24 * uIntensity);
        color = mix(color, uAccent, streak * segment * 0.38 * uIntensity);
      // void-6 · Chemical burn
      } else if (atlasVariant < 6.5) {
        float2 center = seedOffset * 0.2 + closedDrift * 0.035;
        float reaction = fbm(q * 2.34 + closedDriftTwo * 0.08);
        float field = length(p - center) + (reaction - 0.5) * 0.34;
        float inside = 1.0 - smoothstep(0.42, 0.58, field);
        float edge = 1.0 - smoothstep(0.0, 0.075, abs(field - 0.5));
        color = mix(uColorA, uColorB, inside * 0.52 * uIntensity);
        color = mix(color, uAccent, edge * 0.56 * uIntensity);
      // void-7 · Black tide
      } else {
        float tideA = smoothstep(-0.12, 0.12, p.y + 0.34 + sin(p.x * 2.0 + sin(uPhase) * 0.4 + seedAngle) * 0.08);
        float tideB = smoothstep(-0.1, 0.14, p.y + 0.08 + sin(p.x * 2.8 - sin(uPhase * 2.0) * 0.32 + seedAngle * 0.7) * 0.07);
        float tideC = smoothstep(-0.1, 0.16, p.y - 0.18 + sin(p.x * 3.7 + sin(uPhase) * 0.25 + seedAngle * 1.2) * 0.05);
        float edgeA = 1.0 - smoothstep(0.0, 0.08, abs(p.y + 0.34 + sin(p.x * 2.0 + sin(uPhase) * 0.4 + seedAngle) * 0.08));
        color = mix(uColorA, uColorB, (tideA * 0.14 + tideB * 0.18 + tideC * 0.22) * uIntensity);
        color = mix(color, uAccent, edgeA * 0.18 * uIntensity);
      }


    } else if (uMode < 5.5) {
      float3 mapBase = mix(uColorA, uColorB, smoothstep(-0.9, 0.9, q.y) * 0.24);

      // cutting-map-0 · Contour notes
      if (atlasVariant < 0.5) {
        float terrain = fbm(q * 1.55 + closedDrift * 0.055);
        float contourCell = abs(fract((terrain + q.y * 0.16) * 11.0) - 0.5);
        float contours = 1.0 - smoothstep(0.455, 0.5, contourCell);
        float quietCentre = smoothstep(0.12, 0.5, abs(q.x)) + smoothstep(0.16, 0.64, abs(q.y));
        color = mapBase;
        color = mix(color, uAccent, contours * min(1.0, quietCentre) * 0.14 * uIntensity);
      // cutting-map-1 · Folded atlas
      } else if (atlasVariant < 1.5) {
        float2 foldUv = rotate2d(seedAngle * 0.08) * q;
        float spine = 1.0 - smoothstep(0.0, 0.065, abs(foldUv.x + closedDrift.x * 0.025));
        float crease = 1.0 - smoothstep(0.0, 0.18, abs(foldUv.y - 0.1));
        float region = smoothstep(-0.08, 0.08, foldUv.x + sin(foldUv.y * 3.1) * 0.045);
        color = mix(mapBase, uColorB, region * 0.22 * uIntensity);
        color = mix(color, uAccent, (spine * 0.16 + crease * 0.055) * uIntensity);
      // cutting-map-2 · Route thread
      } else if (atlasVariant < 2.5) {
        float routeY = sin(q.x * 2.35 + seedAngle) * 0.16 + sin(q.x * 5.1 - uPhase) * 0.025;
        float route = 1.0 - smoothstep(0.012, 0.035, abs(q.y - routeY));
        float localA = gridLine(q.x + seedOffset.x * 0.04, 4.0, 0.012);
        float localB = gridLine(q.y + seedOffset.y * 0.04, 5.0, 0.01);
        color = mapBase;
        color = mix(color, uColorB, max(localA, localB) * 0.065 * uIntensity);
        color = mix(color, uAccent, route * 0.24 * uIntensity);
      // cutting-map-3 · Parcel lines
      } else if (atlasVariant < 3.5) {
        float2 parcels = q + float2(sin(q.y * 2.2), sin(q.x * 1.8)) * 0.045 + closedDrift * 0.02;
        float rules = max(gridLine(parcels.x, 3.0, 0.014), gridLine(parcels.y, 4.0, 0.012));
        float subdivision = max(gridLine(parcels.x + 0.08, 7.0, 0.006), gridLine(parcels.y - 0.05, 9.0, 0.005));
        color = mapBase;
        color = mix(color, uAccent, (rules * 0.13 + subdivision * 0.045) * uIntensity);
      // cutting-map-4 · Registration field
      } else if (atlasVariant < 4.5) {
        float2 registerCell = fract((q + seedOffset * 0.05) * 3.2) - 0.5;
        float horizontal = softBand(registerCell.y, 0.0, 0.009, 0.018) * (1.0 - smoothstep(0.1, 0.34, abs(registerCell.x)));
        float vertical = softBand(registerCell.x, 0.0, 0.009, 0.018) * (1.0 - smoothstep(0.1, 0.34, abs(registerCell.y)));
        float crosses = max(horizontal, vertical);
        float trim = max(softBand(abs(p.x), aspect * 0.42, 0.008, 0.018), softBand(abs(p.y), 0.42, 0.008, 0.018));
        color = mapBase;
        color = mix(color, uAccent, (crosses * 0.13 + trim * 0.08) * uIntensity);
      // cutting-map-5 · Coastline proof
      } else if (atlasVariant < 5.5) {
        float erosion = fbm(float2(q.y * 1.8, q.x * 1.2) + closedDriftTwo * 0.05) - 0.5;
        float coastCoordinate = q.x + erosion * 0.32 + sin(q.y * 2.0 + seedAngle) * 0.08;
        float coast = 1.0 - smoothstep(0.012, 0.045, abs(coastCoordinate));
        float shelfA = 1.0 - smoothstep(0.012, 0.038, abs(coastCoordinate - 0.13));
        float shelfB = 1.0 - smoothstep(0.012, 0.038, abs(coastCoordinate - 0.26));
        color = mix(mapBase, uColorB, smoothstep(-0.1, 0.12, coastCoordinate) * 0.2 * uIntensity);
        color = mix(color, uAccent, (coast * 0.2 + shelfA * 0.065 + shelfB * 0.04) * uIntensity);
      // cutting-map-6 · Crop window
      } else if (atlasVariant < 6.5) {
        float2 windowCenter = seedOffset * 0.12 + closedDrift * 0.018;
        float2 crop = abs(p - windowCenter) - float2(min(0.42, aspect * 0.34), 0.32);
        float horizontal = (1.0 - smoothstep(0.0, 0.018, abs(crop.y))) * (1.0 - smoothstep(0.04, 0.16, abs(crop.x)));
        float vertical = (1.0 - smoothstep(0.0, 0.018, abs(crop.x))) * (1.0 - smoothstep(0.04, 0.16, abs(crop.y)));
        float proof = softEllipse(p, windowCenter, float2(max(0.28, aspect * 0.32), 0.44), 0.38);
        color = mix(mapBase, uColorB, proof * 0.12 * uIntensity);
        color = mix(color, uAccent, max(horizontal, vertical) * 0.19 * uIntensity);
      // cutting-map-7 · Survey drift
      } else {
        float2 surveyPoint = q + closedDrift * 0.035;
        float bearing = atan2(surveyPoint.y, surveyPoint.x) + seedAngle;
        float radius = length(surveyPoint);
        float arcs = 1.0 - smoothstep(0.012, 0.04, abs(fract(radius * 4.4) - 0.5));
        float spokes = pow(abs(cos(bearing * 6.0)), 28.0) * (1.0 - smoothstep(0.12, 0.92, radius));
        color = mapBase;
        color = mix(color, uAccent, (arcs * 0.1 + spokes * 0.12) * uIntensity);
      }



    } else if (uMode < 6.5) {
      float3 gridBase = mix(uColorA, uColorB, smoothstep(-0.72, 0.72, p.y) * 0.2);

      // grid-0 · Modular field
      if (atlasVariant < 0.5) {
        float fine = max(gridLine(q.x + closedDrift.x * 0.02, 5.0, 0.009), gridLine(q.y + closedDrift.y * 0.02, 5.0, 0.009));
        float major = max(gridLine(q.x + 0.1, 1.0, 0.016), gridLine(q.y - 0.1, 1.0, 0.016));
        color = gridBase;
        color = mix(color, uAccent, (fine * 0.075 + major * 0.12) * uIntensity);
      // grid-1 · Offset ledger
      } else if (atlasVariant < 1.5) {
        float first = max(gridLine(q.x, 4.0, 0.01), gridLine(q.y, 6.0, 0.008));
        float2 offset = seedOffset * 0.07 + closedDrift * 0.025;
        float second = max(gridLine(q.x + offset.x, 4.0, 0.007), gridLine(q.y + offset.y, 6.0, 0.006));
        color = gridBase;
        color = mix(color, uColorB, first * 0.09 * uIntensity);
        color = mix(color, uAccent, second * 0.11 * uIntensity);
      // grid-2 · Quiet thirds
      } else if (atlasVariant < 2.5) {
        float thirdsX = gridLine(uv.x, 3.0, 0.013);
        float thirdsY = gridLine(uv.y, 3.0, 0.013);
        float subdivisions = max(gridLine(uv.x, 9.0, 0.004), gridLine(uv.y, 9.0, 0.004));
        color = gridBase;
        color = mix(color, uAccent, (max(thirdsX, thirdsY) * 0.13 + subdivisions * 0.035) * uIntensity);
      // grid-3 · Baseline rhythm
      } else if (atlasVariant < 3.5) {
        float baselines = gridLine(q.y + closedDrift.y * 0.018, 13.0, 0.006);
        float measures = gridLine(q.x + seedOffset.x * 0.05, 3.0, 0.009);
        float readingBand = 1.0 - smoothstep(0.22, 0.68, abs(q.x));
        color = gridBase;
        color = mix(color, uAccent, (baselines * 0.075 + measures * readingBand * 0.09) * uIntensity);
      // grid-4 · Coordinate crosses
      } else if (atlasVariant < 4.5) {
        float2 cell = fract((q + seedOffset * 0.04 + closedDrift * 0.018) * 4.0) - 0.5;
        float h = softBand(cell.y, 0.0, 0.008, 0.018) * (1.0 - smoothstep(0.08, 0.22, abs(cell.x)));
        float v = softBand(cell.x, 0.0, 0.008, 0.018) * (1.0 - smoothstep(0.08, 0.22, abs(cell.y)));
        float localGlow = 1.0 - smoothstep(0.0, 0.22, length(cell));
        color = gridBase;
        color = mix(color, uAccent, (max(h, v) * 0.15 + localGlow * 0.025) * uIntensity);
      // grid-5 · Broken matrix
      } else if (atlasVariant < 5.5) {
        float2 matrixCell = floor((q + 2.0) * 6.0);
        float keep = step(0.26, hash12(matrixCell + variationKey));
        float matrix = max(gridLine(q.x, 6.0, 0.008), gridLine(q.y, 6.0, 0.008)) * keep;
        float chamber = softEllipse(p, seedOffset * 0.1, float2(max(0.32, aspect * 0.26), 0.5), 0.42);
        color = mix(gridBase, uColorB, chamber * 0.1 * uIntensity);
        color = mix(color, uAccent, matrix * 0.1 * uIntensity);
      // grid-6 · Contact columns
      } else if (atlasVariant < 6.5) {
        float columns = gridLine(q.x + closedDrift.x * 0.015, 6.0, 0.012);
        float rows = gridLine(q.y + seedOffset.y * 0.02, 2.0, 0.008);
        float exposure = smoothstep(-0.66, 0.68, q.y + sin(q.x * 1.7) * 0.04);
        color = mix(gridBase, uColorB, exposure * 0.16 * uIntensity);
        color = mix(color, uAccent, (columns * 0.1 + rows * 0.055) * uIntensity);
      // grid-7 · Perspective register
      } else {
        float depth = max(0.12, q.y + 0.92);
        float recedingX = gridLine(q.x / depth + closedDrift.x * 0.012, 3.0, 0.008);
        float recedingY = gridLine(log(depth) + closedDrift.y * 0.018, 4.0, 0.009);
        float distanceFade = 1.0 - smoothstep(-0.62, 0.58, q.y);
        color = gridBase;
        color = mix(color, uAccent, max(recedingX, recedingY) * (0.055 + distanceFade * 0.06) * uIntensity);
      }



    } else if (uMode < 7.5) {
      float3 waveBase = mix(uColorA, uColorB, smoothstep(-0.82, 0.82, q.y) * 0.28);

      // wave-0 · Tidal horizon
      if (atlasVariant < 0.5) {
        float horizon = q.y + 0.12 + sin(q.x * 2.1 + seedAngle + sin(uPhase) * 0.22) * 0.11;
        float tide = smoothstep(-0.14, 0.16, horizon);
        float edge = 1.0 - smoothstep(0.0, 0.08, abs(horizon));
        color = mix(uColorA, uColorB, tide * 0.52 * uIntensity);
        color = mix(color, uAccent, edge * 0.16 * uIntensity);
      // wave-1 · Nested swell
      } else if (atlasVariant < 1.5) {
        float swellA = 1.0 - smoothstep(0.0, 0.09, abs(q.y + 0.3 + sin(q.x * 1.6 + uPhase * 0.35) * 0.12));
        float swellB = 1.0 - smoothstep(0.0, 0.08, abs(q.y + 0.02 + sin(q.x * 2.1 - uPhase * 0.28 + 1.4) * 0.1));
        float swellC = 1.0 - smoothstep(0.0, 0.075, abs(q.y - 0.27 + sin(q.x * 2.7 + uPhase * 0.22 + 2.2) * 0.075));
        color = waveBase;
        color = mix(color, uAccent, (swellA * 0.12 + swellB * 0.1 + swellC * 0.075) * uIntensity);
      // wave-2 · Interference bed
      } else if (atlasVariant < 2.5) {
        float systemA = sin(q.x * 4.8 + q.y * 2.2 + sin(uPhase) * 0.55);
        float systemB = sin(q.x * 3.1 - q.y * 4.0 - cos(uPhase) * 0.48 + seedAngle);
        float interference = 1.0 - smoothstep(0.06, 0.22, abs((systemA + systemB) * 0.5));
        float bed = 1.0 - smoothstep(0.46, 0.96, abs(q.y));
        color = waveBase;
        color = mix(color, uAccent, interference * bed * 0.11 * uIntensity);
      // wave-3 · Ribbon current
      } else if (atlasVariant < 3.5) {
        float2 current = rotate2d(seedAngle * 0.08 + 0.2) * q;
        float centre = sin(current.x * 2.2 + uPhase * 0.26) * 0.17 + sin(current.x * 4.4 - uPhase * 0.18) * 0.035;
        float ribbon = softBand(current.y, centre, 0.13, 0.2);
        float inner = softBand(current.y, centre + 0.025, 0.025, 0.08);
        color = mix(waveBase, uColorB, ribbon * 0.2 * uIntensity);
        color = mix(color, uAccent, inner * 0.13 * uIntensity);
      // wave-4 · Standing wave
      } else if (atlasVariant < 4.5) {
        float breathingAmplitude = 0.08 + sin(uPhase) * 0.018 * uMotion;
        float standing = sin(q.x * 5.0 + seedAngle) * cos(q.y * 3.0) * breathingAmplitude;
        float centreLine = 1.0 - smoothstep(0.0, 0.07, abs(q.y - standing));
        float chamber = softEllipse(p, seedOffset * 0.08, float2(max(0.34, aspect * 0.31), 0.58), 0.42);
        color = mix(waveBase, uColorB, chamber * 0.12 * uIntensity);
        color = mix(color, uAccent, centreLine * 0.14 * uIntensity);
      // wave-5 · Radial echo
      } else if (atlasVariant < 5.5) {
        float2 echoPoint = p - seedOffset * 0.14 - closedDrift * 0.025;
        float radius = length(echoPoint);
        float echoes = 1.0 - smoothstep(0.43, 0.5, abs(fract(radius * 5.0 - sin(uPhase) * 0.035) - 0.5));
        float fade = 1.0 - smoothstep(0.18, 1.05, radius);
        color = waveBase;
        color = mix(color, uAccent, echoes * fade * 0.13 * uIntensity);
      // wave-6 · Contour current
      } else if (atlasVariant < 6.5) {
        float2 obstacle = q - seedOffset * 0.12;
        float bend = 0.12 / max(0.16, dot(obstacle, obstacle));
        float stream = obstacle.y + bend * obstacle.y + sin(obstacle.x * 2.4 + uPhase * 0.2) * 0.04;
        float lines = 1.0 - smoothstep(0.44, 0.5, abs(fract(stream * 7.0) - 0.5));
        float protectedCentre = smoothstep(0.15, 0.42, length(obstacle));
        color = waveBase;
        color = mix(color, uAccent, lines * protectedCentre * 0.11 * uIntensity);
      // wave-7 · Undertow lines
      } else {
        float lowerField = 1.0 - smoothstep(-0.08, 0.62, q.y);
        float bandA = softBand(q.y, -0.34 + sin(q.x * 1.8 + uPhase * 0.22) * 0.06, 0.055, 0.12);
        float bandB = softBand(q.y, -0.08 + sin(q.x * 2.4 - uPhase * 0.18 + 1.7) * 0.045, 0.04, 0.1);
        float bandC = softBand(q.y, 0.18 + sin(q.x * 3.0 + uPhase * 0.15 + 2.8) * 0.035, 0.03, 0.08);
        color = mix(waveBase, uColorB, lowerField * 0.16 * uIntensity);
        color = mix(color, uAccent, (bandA * 0.1 + bandB * 0.075 + bandC * 0.05) * uIntensity);
      }

uPhase`, so the
 * same shader remains deterministic and loop-safe in preview and export.
 */
export const atelierBackgroundBranch = /* glsl */ `
    } else {
      float2 pigmentDrift = float2(cos(uPhase), sin(uPhase)) * uMotion;
      float2 pigmentDriftTwo = float2(cos(uPhase * 2.0 + 1.1), sin(uPhase * 2.0 + 1.1)) * uMotion;
      float stockTooth = valueNoise(float2(p.x * 118.0, p.y * 176.0) + variationKey * 0.43) - 0.5;
      float stockCloud = fbm(q * 3.1 + variationKey * 0.17) - 0.5;
      float3 atelierStock = max(float3(0.0), uColorA + float3(stockTooth * 0.012 + stockCloud * 0.022) * uIntensity);

      // atelier-0 · Saffron anatomy
      if (atlasVariant < 0.5) {
        float2 centre = seedOffset * 0.08 + pigmentDrift * 0.035;
        float2 washPoint = rotate2d(seedAngle * 0.08) * (p - centre);
        float washNoise = fbm(washPoint * 4.1 + variationKey + pigmentDriftTwo * 0.32) - 0.5;
        float washDistance = length(washPoint / float2(max(0.22, aspect * 0.31), 0.3)) + washNoise * 0.32;
        float wash = 1.0 - smoothstep(0.58, 1.16, washDistance);
        float pooledEdge = 1.0 - smoothstep(0.035, 0.13, abs(washDistance - 0.78));

        float2 inkPoint = p - centre * 0.72;
        float inkRadius = length(inkPoint);
        float inkAngle = atan2(inkPoint.y, inkPoint.x);
        float filamentWarp = (fbm(inkPoint * 6.0 + variationKey) - 0.5) * 2.2;
        float filaments = pow(abs(sin(inkAngle * 11.0 + filamentWarp + seedAngle)), 34.0)
          * smoothstep(0.045, 0.16, inkRadius)
          * (1.0 - smoothstep(0.2, max(0.48, aspect * 0.66), inkRadius));

        float2 noteCell = fract((q + seedOffset * 0.07) * float2(7.0, 11.0)) - 0.5;
        float noteKeep = step(0.83, hash12(floor((q + 2.0) * float2(7.0, 11.0)) + variationKey));
        float notes = softBand(noteCell.y, 0.0, 0.005, 0.012)
          * (1.0 - smoothstep(0.12, 0.39, abs(noteCell.x))) * noteKeep;
        float dripColumn = 1.0 - smoothstep(0.475, 0.5, abs(fract((p.x + seedOffset.x) * 15.0) - 0.5));
        float dripKeep = step(0.88, hash12(float2(floor((p.x + seedOffset.x) * 15.0), variation + 31.0)));
        float drips = dripColumn * dripKeep * smoothstep(-0.38, 0.18, p.y) * (1.0 - smoothstep(0.42, 0.52, p.y));

        color = mix(atelierStock, uColorB, wash * 0.46 * uIntensity);
        color = mix(color, uColorB, pooledEdge * wash * 0.13 * uIntensity);
        color = mix(color, uAccent, (filaments * 0.2 + notes * 0.1 + drips * 0.09) * uIntensity);

      // atelier-1 · Verdigris fresco
      } else if (atlasVariant < 1.5) {
        float2 mineralPoint = rotate2d(-0.18 + seedAngle * 0.04) * (q + pigmentDrift * 0.04);
        float mineralA = fbm(mineralPoint * 1.8 + variationKey * 0.31);
        float mineralB = ridgedFbm(mineralPoint * 2.3 - pigmentDriftTwo * 0.14 + 19.0);
        float glaze = smoothstep(0.34, 0.78, mineralA + mineralB * 0.18);
        float sidePatina = softEllipse(
          p,
          float2(aspect * 0.39, -0.22) + seedOffset * 0.045 + pigmentDrift * 0.018,
          float2(max(0.22, aspect * 0.43), 0.38),
          0.68
        );
        float upperPatina = softEllipse(
          p,
          float2(-aspect * 0.37, 0.34) - seedOffset * 0.035,
          float2(max(0.18, aspect * 0.31), 0.22),
          0.72
        );
        float2 archCentre = float2(-aspect * 0.18, 0.12) + seedOffset * 0.08;
        float archRadius = length(p - archCentre);
        float arches = 1.0 - smoothstep(0.455, 0.5, abs(fract(archRadius * 6.5) - 0.5));
        arches *= 1.0 - smoothstep(0.12, max(0.54, aspect * 0.75), archRadius);
        float seam = softBand((rotate2d(0.34) * p).y, -0.07 + pigmentDrift.y * 0.02, 0.008, 0.022);
        float fleck = step(0.987, hash12(floor(gl_FragCoord.xy / 5.0) + variationKey));

        color = mix(atelierStock, uColorB, (glaze * 0.4 + sidePatina * 0.2 + upperPatina * 0.1) * uIntensity);
        color = mix(color, uAccent, (arches * 0.15 + seam * 0.09 + fleck * 0.18) * uIntensity);

      // atelier-2 · Ultramarine ledger
      } else if (atlasVariant < 2.5) {
        float2 ledgerPoint = q + float2(pigmentDrift.x * 0.05, pigmentDriftTwo.y * 0.035);
        float poolNoise = fbm(ledgerPoint * 3.7 + variationKey * 0.29) - 0.5;
        float2 poolCentre = float2(aspect * 0.3 + seedOffset.x * 0.08, -0.13 + seedOffset.y * 0.04);
        float poolDistance = length((p - poolCentre - pigmentDrift * 0.02) / float2(max(0.34, aspect * 0.5), 0.46)) + poolNoise * 0.31;
        float pool = 1.0 - smoothstep(0.62, 1.18, poolDistance);
        float poolEdge = 1.0 - smoothstep(0.025, 0.095, abs(poolDistance - 0.83));
        float rules = gridLine(uv.y + seedOffset.y * 0.018, 13.0, 0.0045);
        float marginRule = softBand(p.x, -aspect * 0.27, 0.004, 0.011);
        float2 dryPoint = rotate2d(-0.08) * q;
        float dryBrush = softBand(dryPoint.y, -0.22 + sin(dryPoint.x * 2.0 + seedAngle) * 0.035, 0.026, 0.09);
        dryBrush *= smoothstep(0.38, 0.72, valueNoise(float2(dryPoint.x * 28.0, dryPoint.y * 7.0) + variationKey));

        color = mix(atelierStock, uColorB, pool * 0.54 * uIntensity);
        color = mix(color, uColorB, (poolEdge * pool * 0.18 + dryBrush * 0.24) * uIntensity);
        color = mix(color, uAccent, (rules * 0.085 + marginRule * 0.14) * uIntensity);

      // atelier-3 · Rose madder bloom
      } else if (atlasVariant < 3.5) {
        float2 bloomCentre = float2(aspect * 0.25, -0.13) + seedOffset * 0.055;
        float2 bloomPoint = p - bloomCentre - pigmentDrift * 0.025;
        float bloomRadius = length(bloomPoint);
        float bloomAngle = atan2(bloomPoint.y, bloomPoint.x);
        float petalEdge = 0.28 + cos(bloomAngle * 5.0 + seedAngle) * 0.055
          + (fbm(bloomPoint * 5.2 + variationKey + pigmentDriftTwo * 0.2) - 0.5) * 0.07;
        float petals = 1.0 - smoothstep(petalEdge - 0.11, petalEdge + 0.08, bloomRadius);
        float pooledPetal = 1.0 - smoothstep(0.02, 0.075, abs(bloomRadius - petalEdge));
        float heart = softBlob(bloomPoint, float2(0.0), 0.13);
        float veins = pow(abs(sin(bloomAngle * 10.0 + seedAngle)), 40.0)
          * smoothstep(0.07, 0.16, bloomRadius)
          * (1.0 - smoothstep(0.16, 0.34, bloomRadius));
        float fadedWash = softEllipse(p, float2(-aspect * 0.34, 0.31) + seedOffset * 0.045, float2(max(0.2, aspect * 0.33), 0.2), 0.62);
        float petalGhost = softEllipse(p, float2(-aspect * 0.29, -0.3) - seedOffset * 0.03, float2(max(0.15, aspect * 0.22), 0.16), 0.7);

        color = mix(atelierStock, uColorB, (fadedWash * 0.15 + petalGhost * 0.09) * uIntensity);
        color = mix(color, uColorB, petals * 0.48 * uIntensity);
        color = mix(color, uAccent, (pooledPetal * 0.16 + heart * 0.18 + veins * 0.12) * uIntensity);

      // atelier-4 · Charcoal cartography
      } else if (atlasVariant < 4.5) {
        float2 charcoalPoint = rotate2d(0.12 + seedAngle * 0.03)
          * (p - float2(-aspect * 0.12, 0.12) + seedOffset * 0.04 + pigmentDrift * 0.025);
        float smearNoise = ridgedFbm(float2(charcoalPoint.x * 1.3, charcoalPoint.y * 3.5) + variationKey * 0.19);
        float smear = softBand(charcoalPoint.y, sin(charcoalPoint.x * 1.4 + seedAngle) * 0.1, 0.11, 0.26)
          * smoothstep(0.24, 0.82, smearNoise);
        float terrain = fbm(charcoalPoint * 1.7 + variationKey * 0.37);
        float contourCell = abs(fract((terrain + charcoalPoint.y * 0.13) * 13.0) - 0.5);
        float contours = 1.0 - smoothstep(0.46, 0.5, contourCell);
        float gestureY = sin(charcoalPoint.x * 2.1 + seedAngle) * 0.16 + sin(charcoalPoint.x * 5.0) * 0.02;
        float gesture = 1.0 - smoothstep(0.008, 0.032, abs(charcoalPoint.y - gestureY));
        float centreReserve = smoothstep(0.15, 0.42, length(p));
        float edgeRub = softEllipse(
          p,
          float2(-aspect * 0.43, 0.2) + seedOffset * 0.035,
          float2(max(0.22, aspect * 0.38), 0.28),
          0.7
        ) * smoothstep(0.26, 0.78, smearNoise);

        color = mix(atelierStock, uColorB, (smear * 0.29 + edgeRub * 0.18) * uIntensity);
        color = mix(color, uAccent, (contours * centreReserve * 0.13 + gesture * 0.19) * uIntensity);

      // atelier-5 · Gilded palimpsest
      } else if (atlasVariant < 5.5) {
        float2 scriptPoint = rotate2d(-0.11 + seedAngle * 0.025) * q;
        float fadedBlockA = softEllipse(p, float2(-aspect * 0.2, 0.16) + seedOffset * 0.05, float2(max(0.2, aspect * 0.24), 0.3), 0.46);
        float fadedBlockB = softEllipse(p, float2(aspect * 0.25, -0.22) - seedOffset * 0.04, float2(max(0.17, aspect * 0.2), 0.24), 0.52);
        float scriptBand = gridLine(scriptPoint.y + seedOffset.y * 0.025, 15.0, 0.004);
        float scriptKeep = step(0.44, valueNoise(float2(floor((scriptPoint.x + 1.2) * 9.0), floor((scriptPoint.y + 1.0) * 15.0)) + variationKey));
        float script = scriptBand * scriptKeep * (1.0 - smoothstep(0.38, 0.78, abs(scriptPoint.x)));
        float2 arcPoint = p - float2(aspect * 0.18, 0.04) - pigmentDrift * 0.018;
        float arc = 1.0 - smoothstep(0.02, 0.055, abs(length(arcPoint / float2(max(0.24, aspect * 0.35), 0.42)) - 1.0));
        arc *= smoothstep(-0.38, 0.34, arcPoint.x);

        color = mix(atelierStock, uColorB, (fadedBlockA * 0.29 + fadedBlockB * 0.19) * uIntensity);
        color = mix(color, uAccent, (script * 0.12 + arc * 0.17) * uIntensity);

      // atelier-6 · Indigo botanical
      } else if (atlasVariant < 6.5) {
        float2 botanicalPoint = q + float2(pigmentDrift.x * 0.045, 0.0);
        float nightWash = fbm(botanicalPoint * 1.8 + variationKey * 0.23 + pigmentDriftTwo * 0.09);
        float stemX = sin(botanicalPoint.y * 2.8 + seedAngle) * 0.09;
        float stem = 1.0 - smoothstep(0.007, 0.026, abs(botanicalPoint.x - stemX));
        float leaves = 0.0;
        float veins = 0.0;
        for (int leafIndex = 0; leafIndex < 6; leafIndex += 1) {
          float fi = float(leafIndex);
          float leafY = -0.42 + fi * 0.17;
          float side = driftMod(fi, 2.0) < 1.0 ? -1.0 : 1.0;
          float2 leafCentre = float2(sin(leafY * 2.8 + seedAngle) * 0.09 + side * (0.09 + fi * 0.006), leafY);
          float2 leafPoint = rotate2d(side * (0.62 - fi * 0.035)) * (botanicalPoint - leafCentre);
          leaves = max(leaves, softEllipse(leafPoint, float2(0.0), float2(0.105, 0.035), 0.26));
          veins = max(veins, (1.0 - smoothstep(0.003, 0.012, abs(leafPoint.y))) * (1.0 - smoothstep(0.02, 0.1, abs(leafPoint.x))));
        }
        float bloom = softRing(botanicalPoint, float2(stemX, 0.43), float2(0.11, 0.09), 0.12, 0.18);

        color = mix(atelierStock, uColorB, smoothstep(0.34, 0.76, nightWash) * 0.28 * uIntensity);
        color = mix(color, uAccent, (stem * 0.14 + leaves * 0.1 + veins * 0.15 + bloom * 0.08) * uIntensity);

      // atelier-7 · Oxide gesture
      } else {
        float2 gesturePoint = rotate2d(-0.38 + seedAngle * 0.04) * (q + pigmentDrift * 0.03);
        float brushNoise = fbm(float2(gesturePoint.x * 2.2, gesturePoint.y * 7.0) + variationKey * 0.21);
        float strokeA = softBand(gesturePoint.y, -0.18 + sin(gesturePoint.x * 1.7 + seedAngle) * 0.06, 0.055, 0.14);
        float strokeB = softBand(gesturePoint.y, 0.04 + sin(gesturePoint.x * 2.1 + 1.9) * 0.045, 0.035, 0.11);
        float strokeC = softBand(gesturePoint.y, 0.23 + sin(gesturePoint.x * 2.8 + 3.1) * 0.03, 0.022, 0.08);
        float dryMask = smoothstep(0.3, 0.72, brushNoise);
        float2 orbitPoint = p - seedOffset * 0.08 - pigmentDriftTwo * 0.018;
        float orbit = 1.0 - smoothstep(0.016, 0.052, abs(length(orbitPoint / float2(max(0.26, aspect * 0.34), 0.39)) - 1.0));
        float dripColumn = 1.0 - smoothstep(0.47, 0.5, abs(fract((p.x + seedOffset.x) * 19.0) - 0.5));
        float dripKeep = step(0.9, hash12(float2(floor((p.x + seedOffset.x) * 19.0), variation + 73.0)));
        float drips = dripColumn * dripKeep * smoothstep(-0.42, 0.26, p.y);
        float oxideVeilA = softEllipse(
          p,
          float2(-aspect * 0.38, 0.24) + seedOffset * 0.035 + pigmentDrift * 0.015,
          float2(max(0.2, aspect * 0.4), 0.25),
          0.72
        );
        float oxideVeilB = softEllipse(
          p,
          float2(aspect * 0.42, -0.3) - seedOffset * 0.025,
          float2(max(0.17, aspect * 0.31), 0.2),
          0.74
        );

        color = mix(atelierStock, uColorB, (oxideVeilA * 0.15 + oxideVeilB * 0.1) * uIntensity);
        color = mix(color, uColorB, (strokeA * 0.42 + strokeB * 0.31 + strokeC * 0.21) * dryMask * uIntensity);
        color = mix(color, uAccent, (orbit * 0.16 + drips * 0.11) * uIntensity);
      }
    }


    // Shared treatment: aspect-correct vignette. Grain remains a distinct
    // finishing plate so paper texture, atmosphere and camera stock never blur
    // into one generic noise control.
    float centerMask = 1.0 - smoothstep(0.18, 0.92, dot(p, p));
    color *= mix(1.0 - uVignette * 0.62, 1.0, centerMask);
    float4 output = float4(color, 1.0);
    output.rgb = driftToSRGB(output.rgb);

    // Held 12 fps, two-scale monochrome grain: visible in dark rooms without
    // devolving into single-pixel television snow.
    float displayLuminance = dot(output.rgb, float3(0.2126, 0.7152, 0.0722));
    float grainControl = clamp(uGrain, 0.0, 0.6);
    float grainAmount = 0.026 * (1.0 - exp(-8.0 * grainControl)) / (1.0 - exp(-4.8));
    float grainToe = smoothstep(0.004, 0.040, displayLuminance);
    float grainResponse = mix(1.0, 1.0 - sqrt(clamp(displayLuminance, 0.0, 1.0)), 0.75);
    float grain = filmGrain(vUv * uResolution, uGrainFrame) * grainAmount * grainResponse * grainToe;
    output.rgb = clamp(output.rgb + float3(grain), 0.0, 1.0);
    output.a = clamp(uOpacity, 0.0, 1.0);
    return float4(driftToLinear(output.rgb) * output.a, output.a);
  }

};
extern "C" { namespace coreimage {
float4 driftBackground(float2 resolution, float2 logicalResolution,
                       float4 colorA, float4 colorB, float4 accent,
                       float4 controls, float4 timeAndSeed, destination dest) {
    DriftShader s;
    s.vUv = dest.coord() / resolution;
    // Grain is defined in logical output pixels, not preview-window pixels.
    s.uResolution = logicalResolution;
    s.uColorA = driftToLinear(colorA.rgb);
    s.uColorB = driftToLinear(colorB.rgb);
    s.uAccent = driftToLinear(accent.rgb);
    s.uMode = timeAndSeed.x; s.uPhase = timeAndSeed.y;
    s.uSeed = timeAndSeed.z; s.uGrainSeed = driftMod(timeAndSeed.z, 4093.0);
    s.uGrainFrame = timeAndSeed.w;
    s.uIntensity = controls.x; s.uMotion = controls.y;
    s.uGrain = controls.z; s.uVignette = controls.w; s.uOpacity = 1.0;
    return s.render();
}
}}
