#!/usr/bin/env python3
"""Offline, mechanical GLSL-to-Metal adaptation of the pinned Drift shader.
No downloads, approximate replacement algorithms, or application-side JS runtime.
Original files and hashes are retained in native/Vendor/DriftBackgrounds.
"""
from pathlib import Path
import re, json, hashlib
ROOT = Path(__file__).resolve().parents[2]
VENDOR = ROOT/'native/Vendor/DriftBackgrounds'
manifest = json.loads((VENDOR/'PROVENANCE.json').read_text())
for name, digest in manifest['files'].items():
    assert hashlib.sha256((VENDOR/name).read_bytes()).hexdigest() == digest, name

def literal(text):
    return text.split('`',1)[1].rsplit('`',1)[0]

source = (VENDOR/'src/backgrounds.ts').read_text()
palettes=[]
for line in source.split('export const BACKGROUND_PALETTES:')[1].split('];',1)[0].splitlines():
    if 'colorA:' not in line: continue
    palettes.append(json.loads(re.sub(r'(\w+):',r'"\1":',line.strip().rstrip(','))))
studies=[]
for args in re.findall(r'^\s*makeStudy\((.+)\),?$',source, re.M):
    values=json.loads('['+args+']')
    keys=['id','name','family','genre','description','paletteId','composition','variation','intensity','motion','grain','vignette']
    studies.append(dict(zip(keys,values)))
assert len(studies)==72 and len(palettes)==28
families=['solid','gradient','aura','paper','void','cutting-map','grid','wave','atelier']
header='// Adapted from pitch.dog Drift @ '+manifest['commit']+'\n// Copyright (C) 2026 pitch.dog and contributors. AGPL-3.0-or-later.\n// Generated by scripts/native/generate-drift-backgrounds.py; do not hand-edit.\n'
swift=header+'import Foundation\n\npublic enum DriftBackgroundCatalog {\n'
swift+='    public static let sourceCommit = '+json.dumps(manifest['commit'])+'\n'
swift+='    public static let palettes: [DriftPalette] = [\n'
for p in palettes:
    swift+='        DriftPalette(id: '+json.dumps(p['id'])+', name: '+json.dumps(p['name'])+', colorA: RGBA(hex: '+json.dumps(p['colorA'])+'), colorB: RGBA(hex: '+json.dumps(p['colorB'])+'), accent: RGBA(hex: '+json.dumps(p['accent'])+')),\n'
swift+='    ]\n    public static let studies: [DriftStudy] = [\n'
for s in studies:
    swift+='        DriftStudy(id: '+json.dumps(s['id'])+', name: '+json.dumps(s['name'])+', family: .'+s['family'].replace('cutting-map','cuttingMap')+', paletteID: '+json.dumps(s['paletteId'])+', composition: '+str(s['composition'])+', variation: '+str(s['variation'])+', intensity: '+str(s['intensity'])+', motion: '+str(s['motion'])+', grain: '+str(s['grain'])+', vignette: '+str(s['vignette'])+'),\n'
swift+='    ]\n}\n'
(ROOT/'native/Sources/GalileoCore/DriftBackgroundCatalog.swift').write_text(swift)
shader=literal((VENDOR/'src/engine/backgroundShader.ts').read_text())
for name in re.findall(r'\$\{(\w+)\}',shader):
    matches=[p for p in (VENDOR/'src/engine/backgroundShaders').glob('*.ts') if ('export const '+name+' ') in p.read_text()]
    assert len(matches)==1,name
    shader=shader.replace('${'+name+'}',literal(matches[0].read_text()))
shader=re.sub(r'precision highp float;\s*','',shader)
shader=shader.replace('varying vec2 vUv;','vec2 vUv;')
shader=shader.replace('uniform ','')
shader=re.sub(r'\bvec([234])\b',r'float\1',shader)
shader=re.sub(r'\bmat2\(([^()]*)\)',lambda m:'float2x2(float2('+','.join(m[1].split(',')[:2])+'), float2('+','.join(m[1].split(',')[2:])+'))',shader)
shader=shader.replace('mat2 ','float2x2 ')
# GLSL mod is floored modulo; MSL fmod would change negative-coordinate patterns.
shader=re.sub(r'\bmod\(', 'driftMod(', shader)
# All atan calls in this pinned source use GLSL's two-argument form.
shader=re.sub(r'\batan\(', 'atan2(', shader)
shader=shader.replace('void main()', 'float4 render()')
shader=shader.replace('gl_FragColor = float4(color, 1.0);','float4 output = float4(color, 1.0);')
shader=shader.replace('#include <colorspace_fragment>','output.rgb = driftToSRGB(output.rgb);')
shader=shader.replace('gl_FragColor','output')
shader=shader.replace('if (output.a <= 0.001) discard;', 'return float4(driftToLinear(output.rgb) * output.a, output.a);')
# Shader constants are structure members in this mechanical translation.
shader=shader.replace('const float ', 'const float ')
preamble=header+'''#include <metal_stdlib>
#include <CoreImage/CoreImage.h>
using namespace metal;
float driftMod(float x, float y) { return x - y * floor(x/y); }
float2 driftMod(float2 x, float y) { return x - y * floor(x/y); }
float2 driftMod(float2 x, float2 y) { return x - y * floor(x/y); }
float3 driftToLinear(float3 c) { return select(pow((c + 0.055) / 1.055, float3(2.4)), c / 12.92, c <= 0.04045); }
float3 driftToSRGB(float3 c) { c = max(c, float3(0)); return select(1.055 * pow(c, float3(1.0/2.4)) - 0.055, c * 12.92, c <= 0.0031308); }
struct DriftShader {
'''
# float2x2 constructors in GLSL and MSL are both column-major.
metal=preamble+shader+'\n};\n'+'''extern "C" { namespace coreimage {
float4 driftBackground(float2 resolution, float2 logicalResolution,
                       float4 colorA, float4 colorB, float4 accent,
                       float4 controls, float4 timeAndSeed, destination dest) {
    DriftShader s;
    s.vUv = dest.coord() / resolution;
    // Grain is defined in logical output pixels, not preview-window pixels.
    s.uResolution = logicalResolution;
    s.uColorA = driftToLinear(colorA.rgb);
    s.uColorB = driftToLinear(colorB.rgb);
    s.uAccent = driftToLinear(accent.rgb);
    s.uMode = timeAndSeed.x; s.uPhase = timeAndSeed.y;
    s.uSeed = timeAndSeed.z; s.uGrainSeed = driftMod(timeAndSeed.z, 4093.0);
    s.uGrainFrame = timeAndSeed.w;
    s.uIntensity = controls.x; s.uMotion = controls.y;
    s.uGrain = controls.z; s.uVignette = controls.w; s.uOpacity = 1.0;
    return s.render();
}
}}
'''
path=ROOT/'native/Sources/GalileoNative/Resources/DriftBackgrounds.metal'
path.parent.mkdir(parents=True,exist_ok=True);path.write_text(metal)
print(f'Generated {len(studies)} studies, {len(palettes)} palettes, {len(metal.splitlines())} Metal lines.')
