const DAY_MS=24*60*60*1000
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v))
const mod=(v,d)=>((v%d)+d)%d
const smoother=v=>{const x=clamp(v,0,1);return x*x*x*(x*(x*6-15)+10)}
function finite(value,label,min,max){if(!Number.isFinite(value)||value<min||value>max)throw new RangeError(`${label}:finite-number-required`);return value}
function validateItem(item){if(!item||typeof item.id!=='string'||!item.id)throw new TypeError('source-required');finite(Number(item.ratio),'ratio',.05,20);return{...item,caption:typeof item.caption==='string'?item.caption:'',kind:item.kind==='video'?'video':'image',failed:Boolean(item.failed)}}
function params(input={}){const direction=input.direction??'forward';if(!['forward','reverse'].includes(direction))throw new TypeError('direction:unsupported');const fit=input.fit??'contain';if(!['contain','cover'].includes(fit))throw new TypeError('fit:unsupported');const background=input.background??'solid-neutral';if(!['solid-neutral','transparent'].includes(background))throw new TypeError('background:unsupported');return{stagePace:finite(Number(input.stagePace??1),'stagePace',.75,1.5),finaleHoldMs:finite(Number(input.finaleHoldMs??2600),'finaleHoldMs',1200,5000),presentationScale:finite(Number(input.presentationScale??1),'presentationScale',.86,1.08),direction,fit,labels:input.labels!==false,background}}
const DEFINITIONS={
  world:{label:'Establish world',base:1500,min:900},
  matte:{label:'Establish Project matte',base:1700,min:1000},
  'guides-caption':{label:'Establish Project apparatus',base:1900,min:1200},
  source:{label:'Present intact source',base:2500,min:1800},
  finale:{label:'Finale hold',base:4000,min:3000}
}
export function presentBuildStages(item,apparatus={},parameters={}){const source=validateItem(item),p=params(parameters),ids=[];if(p.background!=='transparent')ids.push('world');if(apparatus.matte)ids.push('matte');if(apparatus.guides||source.caption.trim())ids.push('guides-caption');ids.push('source','finale');return ids.map(id=>({id,label:DEFINITIONS[id].label,baseMs:id==='finale'?Math.max(DEFINITIONS[id].base,p.finaleHoldMs+1400):DEFINITIONS[id].base,minimumMs:id==='finale'?Math.max(DEFINITIONS[id].min,p.finaleHoldMs+400):DEFINITIONS[id].min,changesOutput:true}))}
function compilePhrase(stages,startMs,durations,prefix,paceScale){let elapsed=startMs;return stages.map(stage=>{const duration=durations.get(stage.id)/paceScale;const value={...stage,id:`${prefix}:${stage.id}`,stageId:stage.id,paceScale,startMs:elapsed,endMs:elapsed+duration,durationMs:duration};elapsed+=duration;return value})}
export function compileBuildTimeline({mode='automatic',item,apparatus={},parameters:input={},fixedDurationMs=0}){if(!['automatic','fixed-duration','directed'].includes(mode))throw new TypeError('mode:unsupported');const p=params(input),stages=presentBuildStages(item,apparatus,p);const baseDurations=new Map(stages.map(s=>[s.id,s.baseMs/p.stagePace]));const minimumDurations=new Map(stages.map(s=>[s.id,s.minimumMs]));const canonicalDurationMs=[...baseDurations.values()].reduce((a,b)=>a+b,0);const readableFloorMs=[...minimumDurations.values()].reduce((a,b)=>a+b,0);let segments=[];if(mode==='fixed-duration'){const requested=finite(Number(fixedDurationMs),'fixedDurationMs',1,DAY_MS);if(requested<readableFloorMs)throw new RangeError(`duration-below-readable-floor:${readableFloorMs}`);const baseSlack=canonicalDurationMs-readableFloorMs;const requestedSlack=requested-readableFloorMs;const scale=baseSlack>0?requestedSlack/baseSlack:0;const durations=new Map(stages.map(s=>[s.id,minimumDurations.get(s.id)+(baseDurations.get(s.id)-minimumDurations.get(s.id))*scale]));const correction=requested-[...durations.values()].reduce((a,b)=>a+b,0);durations.set('finale',durations.get('finale')+correction);segments=compilePhrase(stages,0,durations,'fixed',1)}else{const scales=mode==='directed'?[2,2,1,2]:[1];let elapsed=0;for(let i=0;i<scales.length;i++){const prefix=mode==='directed'?['fast-1','fast-2','regular','fast-close'][i]:'automatic';const part=compilePhrase(stages,elapsed,baseDurations,prefix,scales[i]);segments.push(...part);elapsed=part.at(-1).endMs}}const durationMs=mode==='fixed-duration'?Number(fixedDurationMs):segments.at(-1).endMs;return Object.freeze({mode,durationMs,canonicalDurationMs,readableFloorMs,parameters:Object.freeze(p),stages:Object.freeze(stages.map(Object.freeze)),segments:Object.freeze(segments.map(Object.freeze))})}
function stagePose(stageId,progress,width,height,p){const landscape=width>=height,unit=Math.min(width,height),distance=unit*.16;const slots={world:[landscape?-1.2:-.3,landscape?-.2:-1.2,-1],matte:[landscape?-.7:-.16,landscape?-.1:-.7,-.6],'guides-caption':[landscape?.8:.18,landscape?.18:.8,.35],source:[0,0,.75],finale:[0,0,1]};const slot=slots[stageId];return{x:slot[0]*distance*(1-progress),y:slot[1]*distance*(1-progress),z:slot[2]*distance*progress,opacity:stageId==='world'?.72+progress*.28:progress,scale:stageId==='source'||stageId==='finale'?(.94+.06*progress)*p.presentationScale:.96+.04*progress}}
export function evaluateBuildPreflight({item,timeline,timeMs,stageWidth,stageHeight,reducedMotion=false}){const source=validateItem(item);finite(Number(timeMs),'timeMs',-DAY_MS,DAY_MS*2);finite(Number(stageWidth),'stageWidth',1,16384);finite(Number(stageHeight),'stageHeight',1,16384);if(!timeline?.segments?.length)throw new TypeError('timeline-required');const p=timeline.parameters;if(reducedMotion){const established=timeline.stages.map(s=>({stageId:s.id,label:s.label,progress:1,...stagePose(s.id,1,stageWidth,stageHeight,p)}));return{status:'g10c-preflight',activeStageId:'finale',stageIndex:timeline.stages.length-1,stageCount:timeline.stages.length,progress:1,velocity:0,established,source:{id:source.id,failed:source.failed},staticLedger:true,render:{artworkOpacity:1,artworkFilter:'none',blendMode:'normal',fit:p.fit,transparentWorld:p.background==='transparent'}}}const raw=mod(timeMs,timeline.durationMs);const local=p.direction==='reverse'?(raw===0?timeline.durationMs-Number.EPSILON:timeline.durationMs-raw):raw;const segment=timeline.segments.find(s=>local<s.endMs)??timeline.segments.at(-1);const localProgress=clamp((local-segment.startMs)/Math.max(1,segment.endMs-segment.startMs),0,1),progress=smoother(localProgress);const phraseSegments=timeline.segments.filter(s=>s.id.split(':')[0]===segment.id.split(':')[0]);const stageIndex=phraseSegments.findIndex(s=>s.id===segment.id);const established=phraseSegments.map((stage,index)=>{const amount=index<stageIndex?1:index===stageIndex?progress:0;return{stageId:stage.stageId,label:stage.label,progress:amount,...stagePose(stage.stageId,amount,stageWidth,stageHeight,p)}});return{status:'g10c-preflight',activeStageId:segment.stageId,segmentId:segment.id,stageIndex,stageCount:phraseSegments.length,progress,velocity:(p.direction==='reverse'?-1:1)/Math.max(1,segment.durationMs),established,source:{id:source.id,failed:source.failed},staticLedger:false,render:{artworkOpacity:1,artworkFilter:'none',blendMode:'normal',fit:p.fit,transparentWorld:p.background==='transparent'}}}
export function videoStoryTimeMs(timeMs,durationMs,loop=true){finite(Number(timeMs),'timeMs',-DAY_MS,DAY_MS*2);finite(Number(durationMs),'durationMs',1,DAY_MS);return loop?mod(timeMs,durationMs):clamp(timeMs,0,durationMs)}
