const DAY_MS=24*60*60*1000
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v))
const mod=(v,d)=>((v%d)+d)%d
const smoother=v=>{const x=clamp(v,0,1);return x*x*x*(x*(x*6-15)+10)}
function finite(value,label,minimum,maximum){if(!Number.isFinite(value)||value<minimum||value>maximum)throw new RangeError(`${label}:finite-number-required`);return value}
function parameters(input={}){const travelMs=finite(Number(input.travelMs??1200),'travelMs',200,5000);const holdMs=finite(Number(input.holdMs??650),'holdMs',100,4000);const orientation=input.orientation??'vertical';if(!['vertical','horizontal'].includes(orientation))throw new TypeError('orientation:unsupported');const startSide=input.startSide??'before';if(!['before','after'].includes(startSide))throw new TypeError('startSide:unsupported');const fit=input.fit??'contain';if(!['contain','cover'].includes(fit))throw new TypeError('fit:unsupported');return{travelMs,holdMs,orientation,startSide,fit,labels:input.labels!==false,dividerWidth:finite(Number(input.dividerWidth??2),'dividerWidth',1,8)}}
function validateSources(items){if(!Array.isArray(items)||items.length<2)throw new RangeError('insufficient-input');if(items.length>2)throw new RangeError('ambiguous-extra-input');const roles=new Set();const ids=new Set();for(const item of items){if(!item||typeof item.id!=='string'||ids.has(item.id))throw new TypeError('stable-unique-source-id-required');if(!['before','after'].includes(item.role)||roles.has(item.role))throw new TypeError('unique-before-after-roles-required');ids.add(item.id);roles.add(item.role);finite(Number(item.ratio),'ratio',0.05,20)}if(!roles.has('before')||!roles.has('after'))throw new TypeError('before-after-roles-required');return{before:items.find(x=>x.role==='before'),after:items.find(x=>x.role==='after')}}
function phraseSegments(startMs,paceScale,p){const hold=p.holdMs/paceScale,travel=p.travelMs/paceScale;return[
{id:'start-hold',kind:'hold',startMs,endMs:startMs+hold,from:0,to:0},
{id:'outward',kind:'travel',startMs:startMs+hold,endMs:startMs+hold+travel,from:0,to:1},
{id:'end-hold',kind:'hold',startMs:startMs+hold+travel,endMs:startMs+hold+travel+hold,from:1,to:1},
{id:'return',kind:'travel',startMs:startMs+hold+travel+hold,endMs:startMs+hold+travel+hold+travel,from:1,to:0}
]}
export function compileComparisonTimeline({mode='automatic',parameters:input={},fixedDurationMs=0}){if(!['automatic','fixed-duration','directed'].includes(mode))throw new TypeError('mode:unsupported');const p=parameters(input);const base=2*(p.holdMs+p.travelMs);let segments=[];if(mode==='fixed-duration'){const duration=finite(Number(fixedDurationMs),'fixedDurationMs',600,DAY_MS);const scale=base/duration;segments=phraseSegments(0,scale,p);segments.at(-1).endMs=duration}else{const scales=mode==='directed'?[2,2,1,2]:[1];let elapsed=0;for(let phrase=0;phrase<scales.length;phrase++){const part=phraseSegments(elapsed,scales[phrase],p).map(s=>({...s,id:`${mode==='directed'?['fast-1','fast-2','regular','fast-close'][phrase]:'automatic'}:${s.id}`,phrase,paceScale:scales[phrase]}));segments.push(...part);elapsed=part.at(-1).endMs}}const durationMs=mode==='fixed-duration'?Number(fixedDurationMs):segments.at(-1).endMs;return Object.freeze({mode,durationMs,parameters:Object.freeze(p),segments:Object.freeze(segments.map(Object.freeze))})}
export function evaluateComparison({items,timeline,timeMs,reducedMotion=false,manualReveal=null}){const sources=validateSources(items);finite(Number(timeMs),'timeMs',-DAY_MS,DAY_MS*2);if(!timeline?.segments?.length)throw new TypeError('timeline:required');const p=timeline.parameters;if(manualReveal!==null)finite(Number(manualReveal),'manualReveal',0,1);let reveal,velocity=0,segmentId='manual';if(manualReveal!==null)reveal=Number(manualReveal);else if(reducedMotion){reveal=.5;segmentId='reduced-motion'}else{const local=mod(timeMs,timeline.durationMs);const segment=timeline.segments.find(s=>local<s.endMs)??timeline.segments.at(-1);const progress=(local-segment.startMs)/Math.max(1,segment.endMs-segment.startMs);const eased=segment.kind==='travel'?smoother(progress):0;reveal=segment.from+(segment.to-segment.from)*eased;velocity=segment.kind==='travel'?(segment.to-segment.from)/(segment.endMs-segment.startMs):0;segmentId=segment.id}if(p.startSide==='after')reveal=1-reveal;const clip=p.orientation==='vertical'?{top:0,right:100-reveal*100,bottom:0,left:0}:{top:0,right:0,bottom:100-reveal*100,left:0};return{reveal,velocity:p.startSide==='after'?-velocity:velocity,segmentId,orientation:p.orientation,clip,sources:{before:{id:sources.before.id,failed:Boolean(sources.before.failed)},after:{id:sources.after.id,failed:Boolean(sources.after.failed)}},divider:{axis:p.orientation==='vertical'?'x':'y',positionPercent:reveal*100,width:p.dividerWidth},render:{artworkOpacity:1,artworkFilter:'none',blendMode:'normal',fit:p.fit,opaqueOutput:true}}}
export function videoStoryTimeMs(timeMs,durationMs,loop=true){finite(Number(timeMs),'timeMs',-DAY_MS,DAY_MS*2);finite(Number(durationMs),'durationMs',1,DAY_MS);return loop?mod(timeMs,durationMs):clamp(timeMs,0,durationMs)}
